#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_cmsms - Install or remove CMS Made Simple
######             http://www.cmsmadesimple.org/
######             https://docs.cmsmadesimple.org/installation/requirements
######
###### (c) 2017 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="CMS Made Simple"
_slug="cmsms"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function cmsms_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _zone=$(cvw_xml -r system/timezone)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	local _adm_name=$(cvw_xml -r software/$_slug/admin/name)
	local _adm_pass=$(cvw_xml -r software/$_slug/admin/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _phar _file _subdir

	cvw_say -s "Database password .......: $_pass"
	cvw_say -s "Login URL ...............: $(cvw_url -r $_uri)admin/login.php"
	cvw_say -s "Admin user name .........: $_adm_name"
	cvw_say -s "Admin password ..........: $_adm_pass"

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci
	cvw_backup -m $_slug -u $_slug -p $_pass $_slug $_root/app

	_phar="${_slug}-$(cvw_download -v $_slug)-install.php"
	if [[ -s $_root/app/index.php ]] ; then
		if [[ -s $_root/app/README-PHAR.TXT ]] ; then
			cvw_say -s "hiding installer archive"
			mv $_root/app/$_phar $_root/app/README-PHAR.TXT $_root
		fi

		_file="$_root/app/config.php"
		cat >$_file.tmp_VW <<-EOF
			<?php
			# CMS Made Simple Configuration File
			# Documentation: /doc/CMSMS_config_reference.pdf
			#
			\$config['dbms'] = 'mysqli';
			\$config['db_hostname'] = 'localhost';
			\$config['db_username'] = '$_slug';
			\$config['db_password'] = '$_pass';
			\$config['db_name'] = '$_slug';
			\$config['db_prefix'] = 'cms_';
			\$config['timezone'] = '$_zone';
			\$config['db_port'] = 3306;

			ini_set('max_execution_time', 120);
		EOF
		cvw_file -m 0444 -v $_file $(cvw_php -s)

		_file="$_root/app/.htaccess"
		if [[ ! -s $_file ]] ; then
			cvw_say -s "copying .htaccess"
			cp $_root/app/doc/htaccess.txt $_file
		fi
		cvw_file -e $_file "s/^#Options/Options/" $(cvw_php -s)

		for _subdir in images fonts js ; do
			mkdir -p $_root/app/assets/$_subdir
		done

		if [[ -d /var/local/backup/$_slug/last/mysql && \
		      -d /var/local/backup/$_slug/last/dirs  && \
		      -x /usr/local/bin/bkup.$_slug          && \
		      -x /usr/local/bin/rstr.$_slug ]] ; then
			cvw_say -s "updating / syncing backup"
			/usr/local/bin/bkup.$_slug
		fi
	else
		cvw_unpack -s -i $_slug $_root/app README-PHAR.TXT
		cvw_say -s "waiting for install: https://$_fqdn/$_phar"
	fi
	chown -R apache:apache $_root/app

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function cmsms_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	cvw_backup -z $_slug
	cvw_mysql -z $_slug $_slug
	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				cmsms_install
			else
				cmsms_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

