#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_grav - Install or remove Grav CMS
######            https://getgrav.org/
######            https://learn.getgrav.org/basics/installation
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Grav CMS"
_slug="grav"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function grav_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/php || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	#local _lang=$(cvw_xml -r system/language)
	local _uri=$(cvw_xml -r software/$_slug/uri)
	#local _fqdn=$(cvw_xml -r host/fqdn)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _app=$_root/app
	local _file _subdir

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      Username ................: $(cvw_xml -r software/$_slug/admin/username)
			      Email ...................: $(cvw_xml -r software/$_slug/admin/email)
			      Password ................: $(cvw_xml -r software/$_slug/admin/password)
			      Full name ...............: $(cvw_xml -r software/$_slug/admin/fullname)
			      Title ...................: $(cvw_xml -r software/$_slug/title)
			      Login URL ...............: $(cvw_url -r $_uri)admin"
		EOF
		[[ -s /tmp/cvw/error ]] && exit 1
	fi

	cvw_backup -m $_slug -u $_slug -p $_pass $_slug

	cvw_unpack -u apache -i $_slug $_app index.php

	_file=$_app/.htaccess
	cvw_file -u apache -e $_file "s|^# \(RewriteBase .*\)|\1|" $(cvw_php -s)
	cvw_file -u apache -e $_file "s|^\(RewriteBase\).*|\1 $_uri|" $(cvw_php -s)

	_file="/etc/profile.d/alias_$_slug.sh"
	cat >$_file.tmp_VW <<-EOF
		#
		# shell aliases for $_name
		#
		alias g-a='cd $_app'
		alias g-c='cd $_app/user/config'
		alias g-i='cd $_app/images'
		alias g-l='cd $_app/system/languages'
		alias g-s='cd $_app/system'
		alias g-t='cd $_app/system/templates'
		alias g-u='cd $_app/user'
		#
		alias g-='cat $_file'
	EOF
	cvw_file -v $_file

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function grav_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		cvw_backup -z $_slug
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				grav_install
			else
				grav_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

