#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_dokuwiki - Install or remove DokuWiki
######                https://www.dokuwiki.org/dokuwiki
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="DokuWiki"
_slug="dokuwiki"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function dokuwiki_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/php || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _conf _file _subdir

	cvw_unpack -i $_slug $_root/app index.php
	for _subdir in conf data ; do
		mkdir -p $_root/app/$_subdir
		chown -R apache $_root/app/$_subdir
	done

	_file="$_root/app/.htaccess"
	cat >$_file.tmp_VW <<-EOF
		## Enable this to restrict editing to logged in users only

		## You should disable Indexes and MultiViews either here or in the
		## global config. Symlinks maybe needed for URL rewriting.
		Options -Indexes -MultiViews +FollowSymLinks

		## make sure nobody gets the htaccess, README, COPYING or VERSION files
		<Files ~ "^([\\._]ht|README$|VERSION$|COPYING$)">
		   Require all denied
		</Files>

		## Don't allow access to git directories
		<IfModule alias_module>
		   RedirectMatch 404 /\\.git
		</IfModule>

		## Uncomment these rules if you want to have nice URLs using
		## \$conf['userewrite'] = 1 - not needed for rewrite mode 2
		RewriteEngine on
		#
		RewriteRule ^_media/(.*)              lib/exe/fetch.php?media=\$1  [QSA,L]
		RewriteRule ^_detail/(.*)             lib/exe/detail.php?media=\$1  [QSA,L]
		RewriteRule ^_export/([^/]+)/(.*)     doku.php?do=export_\$1&id=\$2  [QSA,L]
		RewriteRule ^\$                        doku.php  [L]
		RewriteCond %{REQUEST_FILENAME}       !-f
		RewriteCond %{REQUEST_FILENAME}       !-d
		RewriteRule (.*)                      doku.php?id=\$1  [QSA,L]
		RewriteRule ^index.php\$               doku.php
		#
		## Not all installations will require the following line.  If you do,
		## change "/dokuwiki" to the path to your dokuwiki directory relative
		## to your document root.
		RewriteBase $_uri
		#
		## If you enable DokuWikis XML-RPC interface, you should consider to
		## restrict access to it over HTTPS only! Uncomment the following two
		## rules if your server setup allows HTTPS.
		#RewriteCond %{HTTPS} !=on
		#RewriteRule ^lib/exe/xmlrpc.php$      https://%{SERVER_NAME}%{REQUEST_URI} [L,R=301]
	EOF
	cvw_file -v $_dest $(cvw_php -s)

	_file="$_root/app/conf/local.php"
	cat >$_file.tmp_VW <<-EOF
		<?php
		\$conf['title']       = 'Example Wiki';
		\$conf['lang']        = 'de';
		\$conf['tagline']     = 'This is the tagline';
		\$conf['useacl']      = 1;
		\$conf['superuser']   = 'volker';
	EOF
	if [[ -s $_file ]] ; then
		if [[ -r $_root/app/install.php ]] ; then
			cvw_say -s "hiding install.php"
			rm -rf $_root/install.php # just in case
			mv $_root/app/install.php $_root/install.php
		fi
		cvw_borgclient -d $_root/app/conf
		cvw_borgclient -d $_root/app/data
	else
		cvw_say -s "waiting for installation"
	fi
	cvw_file -v $_dest $(cvw_php -s)

	_file="$_root/app/conf/acl.auth.php"
	cat >$_file.tmp_VW <<-EOF
		# acl.auth.php
		# <?php exit()?>
		# Don't modify the lines above
		#
		# Access Control Lists
		#
		# Editing this file by hand shouldn't be necessary. Use the ACL
		# Manager interface instead.
		#
		# If your auth backend allows special char like spaces in groups
		# or user names you need to urlencode them (only chars <128, leave
		# UTF-8 multibyte chars as is)
		#
		# none   0
		# read   1
		# edit   2
		# create 4
		# upload 8
		# delete 16

		*               @ALL        8
	EOF
	cvw_file -v $_dest $(cvw_php -s)

	_file="$_root/app/conf/users.auth.php"
	cat >$_file.tmp_VW <<-EOF
		# users.auth.php
		# <?php exit()?>
		# Don't modify the lines above
		#
		# Userfile
		#
		# Format:
		#
		# login:passwordhash:Real Name:email:groups,comma,seperated

	EOF
	cvw_file -v $_dest $(cvw_php -s)

	if cvw_xml -a software/nginx ; then
		_file="/tmp/cvw/nginx.options"
		cat >$_file <<-EOF
			    location ~ /(data|conf|bin|inc)/ {
			      deny all;
			    }
		EOF
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function dokuwiki_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				dokuwiki_install
			else
				dokuwiki_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

