#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_magento - Install or remove Magento Shop
######               http://docs.magento.com/m2/ce/user_guide/getting-started.html
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Magento Shop"
_slug="magento"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function magento_install_native
{
	cvw_say -h "Installing $_name (native)"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _conf _file _check _subdir _dist

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci

	cvw_unpack -f /var/local/cvw/$_slug/Magento-CE-2.1.3.tar.bz2 $_root/app index.php

if false ; then
	if [[ -r $_root/app/config-dist.php ]] ; then
		cvw_say -a "waiting for web install"
		mv $_root/app/config-dist.php       $_root/app/config.php
		mv $_root/app/admin/config-dist.php $_root/app/admin/config.php
	fi

	if [[ -s $_root/app/.htaccess.txt ]] ; then
		cvw_say -s "activating .htaccess"
		mv $_root/app/.htaccess.txt $_root/app/.htaccess
	fi

	if [[ -s $_root/app/config.php && -d $_root/app/install ]] ; then
		cvw_say -s "hiding install directory"
		rm -rf $_root/install # just in case
		mv $_root/app/install $_root/install
	fi

	if [[ -r /root/.$_slug ]] ; then
		chown -R apache:apache $_root/app
		rm -f /root/.$_slug
		cvw_say -a "$_slug ready for update - be careful"
	elif grep -q "VQMod::bootup" $_root/app/admin/index.php ; then
		chown -R root:root $_root/app
		chown -R apache $_root/app/image
		chown -R apache $_root/app/system/storage
		cvw_say -s "running in production"
	else
		chown -R apache:apache $_root/app
		cvw_say -a "please run https://$_fqdn$_uri/vqmod/install/"
	fi
fi

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_borgclient -m $_slug
	cvw_borgclient -d $_root/app

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function magento_install_bitnami
{
	cvw_say -h "Installing $_name (Bitnami)"
	cvw_xml -a software/bitnami || cvw_say -f "$_prog: requires bitnami"
	local _root=$(cvw_xml -r system/app_root)/bitnami
	local _lang=$(cvw_xml -r system/language)
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _user=$(cvw_xml -r users/rootmail)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _run _file

	cvw_download -i bitnami_$_slug $_root/Download
	_run=$(cvw_download -f bitnami_$_slug)
	chmod +x $_root/Download/$_run

	_file=$_root/Download/$_slug.options
	cat >$_file.tmp_VW <<-EOF
		installer-language=${_lang%_*}
		prefix=$_root/app
		base_user=$_user
		base_user_name=$(cvw_xml -r users/user:$_user/info)
		base_mail=$_user@${_fqdn#*.}
		base_password=$(cvw_xml -r users/user:$_user/password)
		magento_site=$_fqdn
		smtp_enable=0
		baseinstalltype=production
		magento_admin_pass=$(cvw_xml -r software/$_slug/password)
		launch_cloud=0
	EOF
	[[ -s /tmp/cvw/error ]] && exit 1
	cvw_file -v $_file bitnami:apache bitnami:mysql

	if [[ ! -d $_root/app/apps/$_slug ]] ; then
		cvw_say -s "running $_run"
		$_root/Download/$_run --mode unattended --optionfile $_file 2>>/tmp/cvw/error
	fi

	cvw_say -o "$_slug"
}


function magento_remove_native
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name (native)"
		cvw_mysql -z $_slug $_slug
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


function magento_remove_bitnami
{
	local _root=$(cvw_xml -r system/app_root)/bitnami
	local _file=$_root/app/apps/$_slug/uninstall

	if [[ -x $_file ]] ; then
		cvw_say -h "Removing $_name (Bitnami)"
		cvw_say -s "running $_file"
		$_file --mode unattended
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				if cvw_xml -t software/$_slug/bitnami ; then
					magento_install_bitnami
				else
					magento_install_native
				fi
			else
				if cvw_xml -t software/$_slug/bitnami ; then
					magento_remove_bitnami
				else
					magento_remove_native
				fi
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

