#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_prestashop - Install or remove PrestaShop
######                  https://www.prestashop.com/
######                  http://doc.prestashop.com/display/PS17/Getting+started
######                  http://doc.prestashop.com/display/PS17/Installing+PrestaShop+using+the+command-line+script
######
###### (c) 2016 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="PrestaShop"
_slug="prestashop"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function prestashop_install_native
{
	cvw_say -h "Installing $_name (native)"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _lang=$(cvw_xml -r system/language)
	local _zone=$(cvw_xml -r system/timezone)
	local _shop=$(cvw_xml -r software/$_slug/shopname)
	local _first=$(cvw_xml -r software/$_slug/admin/first_name)
	local _last=$(cvw_xml -r software/$_slug/admin/last_name)
	local _pswd=$(cvw_xml -r software/$_slug/admin/password)
	local _email=$(cvw_xml -r software/$_slug/admin/email)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _conf _file _check _subdir _dist

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci
	cvw_backup -m $_slug -u $_slug -p $_pass $_slug

	cvw_unpack -m -s -u apache -i $_slug $_root/app index.php

	_file="prestashop.zip"
	if [[ -s $_root/app/$_file ]] ; then
		cvw_say -s "unzipping $_file"
		rm -rf $_root/$_file # just in case
		mv $_root/app/$_file $_root/$_file
		rm -rf $_root/app
		mkdir -p $_root/app
		unzip -q -o -d $_root/app $_root/$_file
	fi
	chown root:root $_root/$_file
	chown -R apache:apache $_root/app

	_subdir="$_root/app/install"
	if [[ -d $_subdir ]] ; then
		cvw_say -s "running command line installer"
		pushd $_subdir >/dev/null
		php index_cli.php 		\
			--language=${_lang%_*}	\
			--timezone="$_zone"	\
			--domain=$_fqdn$_uri	\
			--db_server=localhost	\
			--db_name=$_slug	\
			--db_user=$_slug	\
			--db_password="$_pass"	\
			--name="$_shop"		\
			--country=${_lang%_*}	\
			--firstname="$_first"	\
			--lastname="$_last"	\
			--password="$_pswd"	\
			--email="$_email"	\
			--newsletter=0
		popd >/dev/null
		rm -rf $_root/install # just in case
		mv $_subdir $_root/install
	fi
	chown root:root $_root/install

if false ; then
	if [[ -s $_root/app/app/config/parameters.php ]] ; then
		cvw_say -s "hiding install directory"
		rm -rf $_root/install # just in case
		mv $_root/app/install $_root/install
	fi

	if [[ -d /var/local/backup/$_slug/last/mysql && \
	      -d /var/local/backup/$_slug/last/dirs  && \
	      -x /usr/local/bin/bkup.$_slug          && \
	      -x /usr/local/bin/rstr.$_slug ]] ; then
		cvw_say -s "updating / syncing backup"
		/usr/local/bin/bkup.$_slug
	fi
fi

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function prestashop_install_bitnami
{
	cvw_say -h "Installing $_name (Bitnami)"
	cvw_xml -a software/bitnami || cvw_say -f "$_prog: requires bitnami"
	local _root=$(cvw_xml -r system/app_root)/bitnami
	local _lang=$(cvw_xml -r system/language)
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _user=$(cvw_xml -r users/rootmail)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _run _file

	cvw_download -i bitnami_$_slug $_root/Download
	_run=$(cvw_download -f bitnami_$_slug)
	chmod +x $_root/Download/$_run

	_file=$_root/Download/$_slug.options
	cat >$_file.tmp_VW <<-EOF
		installer-language=${_lang%_*}
		prefix=$_root/app
		base_user=$_user
		base_user_name=$(cvw_xml -r users/user:$_user/info)
		base_mail=$_user@${_fqdn#*.}
		base_password=$(cvw_xml -r users/user:$_user/password)
		prestashop_site=$_fqdn
		smtp_enable=0
		launchbeetailer=0
		launch_cloud=0
	EOF
	[[ -s /tmp/cvw/error ]] && exit 1
	cvw_file -v $_file bitnami:apache bitnami:mysql

	if [[ ! -d $_root/app/apps/$_slug ]] ; then
		cvw_say -s "running $_run"
		$_root/Download/$_run --mode unattended --optionfile $_file 2>>/tmp/cvw/error
	fi

	cvw_say -o "$_slug"
}


function prestashop_remove_native
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	cvw_backup -z $_slug
	cvw_mysql -z $_slug $_slug
	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name (native)"
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


function prestashop_remove_bitnami
{
	local _root=$(cvw_xml -r system/app_root)/bitnami
	local _file=$_root/app/apps/$_slug/uninstall

	if [[ -x $_file ]] ; then
		cvw_say -h "Removing $_name (Bitnami)"
		
		cvw_say -s "running $_file"
		$_file --mode unattended

		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				if cvw_xml -t software/$_slug/bitnami ; then
					prestashop_install_bitnami
				else
					prestashop_install_native
				fi
			else
				if cvw_xml -t software/$_slug/bitnami ; then
					prestashop_remove_bitnami
				else
					prestashop_remove_native
				fi
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

