#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_memcache - Install or remove Memcache
######                http://memcached.org/
######
###### (c) 2016-2017 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Memcache"
_slug="memcache"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		    or: $_prog -g   Generate config template
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function memcache_generate
{
	cat <<-EOF
	    <memcache active="true">
	    </memcache>

	EOF
	exit 0
}


function memcache_install
{
	cvw_say -h "Installing $_name"

	cvw_rpm -i memcached
	cvw_rpm -i memcached-devel
	cvw_service -s memcached

	cvw_say -o "$_slug"
}


function memcache_remove
{
	if cvw_service -c memcached ; then
		cvw_say -h "Removing $_name"

		cvw_service -d memcached
		cvw_rpm -e memcached-devel
		cvw_rpm -e memcached

		cvw_say -o "$_slug:remove"
	fi
}


while getopts ":ig" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				memcache_install
			else
				memcache_remove
			fi
			exit 0
		;;

		g)
			memcache_generate
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

