#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_redis - Install or remove redis (key value store)
######             http://redis.io/
######
###### (c) 2016 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Redis"
_slug="redis"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function redis_install
{
	cvw_say -h "Installing $_name"

	cvw_rpm -i redis
	cvw_service -s redis

	cvw_say -o "$_slug"
}


function redis_remove
{
	if cvw_service -c redis ; then
		cvw_say -h "Removing $_name"

		cvw_service -d redis

		cvw_say -o "$_slug:remove"
	fi
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				redis_install
			else
				redis_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

