#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_xiopo - Install or remove Xiopo Newsmailer
######                http://xiopo.de/
######                http://xiopo.de/1l22l26-xiopo-newsmailer-free-edition-installaion.html
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Xiopo Newsmailer"
_slug="xiopo"


_archive="/var/lib/cvw_cfg/files/misc/XiopoNewsmailer_Free_Edition_5_0.zip"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function xiopo_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	local _fqdn=$(cvw_xml -r host/fqdn)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _file

	cvw_backup -m $_slug -u $_slug -p $_pass $_slug \
		$_root/app

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci

	# cvw_unpack -i $_slug $_root/app index.php
	if [[ ! -d $_root/upload/admin ]] ; then
		unzip -q -d $_root $_archive
	fi
	chmod -R go-w $_root/upload
	find $_root/upload -type f -exec chmod a-x {} \;
	if [[ ! -h $_root/app ]] ; then
		ln -nfs $_root/upload $_root/app
	fi

	_file=$_root/app/.htaccess
	cp $_root/tools/htacces_2/.htaccess $_file.tmp_VW
	cvw_file -v $_file $(cvw_php -s)

	if [[ -s $_root/app/sql_access/sql_access.php ]] ; then
		chown -R root:root $_root
		if [[ -d $_root/app/install ]] ; then
			cvw_say -s "hiding install dir"
			mv $_root/app/install $_root
		fi
	else
		chown -R apache:apache $_root
		cvw_say -s "waiting for install: https://$_fqdn$_uri/install/"
	fi

if false ; then
	_file=$(cvw_download -f $_slug)
	cvw_unpack -u apache -i $_slug $_root/Download "._${_file%.zip}"
	[[ -h $_root/app ]] || ln -nfs $_root/Download/shoproot $_root/app

	if grep -q $_pass $_root/app/includes/configure.php ; then
		chmod 0444 $_root/app/includes/configure.php

		if [[ -d $_root/app/_installer ]] ; then
			cvw_say -s "hiding install directory"
			rm -rf $_root/_installer # just in case
			mv $_root/app/_installer $_root/_installer
			chown -R root:root $_root/_installer
		fi

		if [[ -s $_root/app/_.htaccess ]] ; then
			_file="$_root/app/.htaccess"
			cp $_root/app/_.htaccess $_file
			cvw_file -e $_file "s|^AddDefaultCharset.*|AddDefaultCharset UTF-8|"
			cvw_file -e $_file "s|^RewriteBase.*|RewriteBase ${_uri%/}/|"
		fi
	else
		cvw_say -s "waiting for install: https://$_fqdn$_uri/_installer"
	fi
fi

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				xiopo_install
			else
				cvw_php -z $_slug
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

