#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_docker - Install or remove Docker and Compose
######              https://docs.docker.com/
######              https://docs.docker.com/compose/
######
###### (c) 2016 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Docker and Compose"
_slug="docker"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function docker_install
{
	cvw_say -h "Installing $_name"
	local _file _port

	_file="/etc/yum.repos.d/docker.repo"
	cat >$_file.tmp_VW <<-EOF
		[dockerrepo]
		name=Docker Repository
		baseurl=https://yum.dockerproject.org/repo/main/centos/7/
		enabled=1
		gpgcheck=1
		priority=19
		gpgkey=https://yum.dockerproject.org/gpg
	EOF
	cvw_file -v $_file

	cvw_yum -a docker
	cvw_rpm -i docker-engine
	cvw_rpm -i docker-engine-selinux
	cvw_service -S docker

	cvw_download -i docker_compose /usr/local/bin
	pushd /usr/local/bin >/dev/null
	chmod +x docker-compose-Linux-x86_64 2>>/tmp/cvw/error
	ln -nfs docker-compose-Linux-x86_64 docker-compose
	popd >/dev/null
	[[ -s /tmp/cvw/error ]] && exit 1

	cvw_xml -l software/$_slug/tcp_port | sort -u | while read _port ; do
		cvw_firewall -t $_port
	done

	cvw_say -o "$_slug"
}


function docker_remove
{
	if cvw_rpm -c docker-engine ; then
		cvw_say -h "Removing $_name"

		rm -f /usr/local/bin/docker-compose*

		cvw_rpm -e docker-engine-selinux
		cvw_rpm -e docker-engine
		rm -f /etc/yum.repos.d/docker.repo

		rm -f /tmp/cvw/error
		cvw_say -o "$_slug:remove"
	fi
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				docker_install
			else
				docker_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

