#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_gogs - Install or remove gogs (Go Git Service)
######            http://gogs.io/
######            https://github.com/gogits/gogs/issues/1202
######
###### (c) 2016 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
######          TODO setup reverse proxy for gogs (not working yet)
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="gogs (Go Git Service)"
_slug="gogs"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function gogs_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	local _canon=$(cvw_xml -r host/fqdn)
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _port=$(cvw_xml -R software/$_slug/port 8888)
	local _pass=$(cvw_xml -r software/$_slug/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	cvw_user -s gogs
	local _home=$(cvw_user -h gogs)
	local _cert="/etc/letsencrypt/live/$_canon"
	local _file

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci
	cvw_backup -m $_slug -u $_slug -p $_pass $_slug \
			$_home/gogs-repositories \
			$_home/app/log

	cvw_unpack -i $_slug $_home/app gogs
	mkdir -p $_home/app/custom/conf

	if [[ -d /var/local/backup/$_slug/last/mysql && \
	      -d /var/local/backup/$_slug/last/dirs  && \
	      -x /usr/local/bin/bkup.$_slug          && \
	      -x /usr/local/bin/rstr.$_slug ]] ; then
		cvw_say -s "updating / syncing backup"
		/usr/local/bin/bkup.$_slug
	fi

	_file="$_home/app/custom/conf/app.ini"
	cat >$_file.tmp_VW <<-EOF
		APP_NAME = $_name
		RUN_USER = gogs
		RUN_MODE = prod

		[repository]
		ROOT = $_home/gogs-repositories

		[server]
		PROTOCOL = http
		ROOT_URL = https://$_canon$_uri
		# CERT_FILE = $_cert/fullchain.pem
		# KEY_FILE  = $_cert/privkey.pem
		DISABLE_SSH = false
		SSH_PORT = $(cvw_xml -R host/ssh_port 22)
		DOMAIN = $_canon
		OFFLINE_MODE = false
		HTTP_ADDR = localhost
		HTTP_PORT = $_port

		[database]
		DB_TYPE = mysql
		HOST = 127.0.0.1:3306
		NAME = $_slug
		USER = $_slug
		PASSWD = $_pass
		SSL_MODE = disable
		PATH = data/gogs.db

		[mailer]
		ENABLED = false

		[service]
	EOF

	if cvw_xml -t software/$_slug/register ; then
		cat >>$_file.tmp_VW <<-EOF
			REGISTER_EMAIL_CONFIRM = true
			ENABLE_NOTIFY_MAIL = false
			DISABLE_REGISTRATION = false
		EOF
	else
		cat >>$_file.tmp_VW <<-EOF
			REGISTER_EMAIL_CONFIRM = false
			ENABLE_NOTIFY_MAIL = false
			DISABLE_REGISTRATION = true
		EOF
	fi

	cat >>$_file.tmp_VW <<-EOF
		ENABLE_CAPTCHA = true
		REQUIRE_SIGNIN_VIEW = true

		[picture]
		DISABLE_GRAVATAR = false

		[session]
		PROVIDER = file

		[log]
		MODE = file
		LEVEL = Info

		[security]
		INSTALL_LOCK = true
		SECRET_KEY = $(cvw_xml -r software/$_slug/secret)
	EOF
	[[ -s /tmp/cvw/error ]] && exit 1
	cvw_file -v $_file gogs
	chown -R gogs:gogs $_home

	_file="/usr/lib/systemd/system/gogs.service"
	cat >$_file.tmp_VW <<-EOF
		[Unit]
		Description=Gogs (Go Git Service)
		Requires=mariadb.service
		After=mariadb.service

		[Service]
		Type=simple
		User=gogs
		Group=gogs
		WorkingDirectory=$_home/app
		ExecStart=$_home/app/gogs web -port $_port
		Restart=always
		Environment=USER=gogs HOME=$_home

		[Install]
		WantedBy=multi-user.target
	EOF
	cvw_file -v $_file gogs

	cvw_service -s gogs

	if cvw_xml -a software/apache ; then
		_conf="/etc/httpd/conf.d/vhost.conf.tmp_VW"
		[[ -s $_conf ]] || cvw_say -f "$_prog: missing $_conf"
		cat >>$_conf <<-EOF

			   <Proxy $_uri>
			      Require all granted
			   </Proxy>
			   ProxyPass        $_uri http://localhost:$_port
			   ProxyPassReverse $_uri http://localhost:$_port
		EOF
		cvw_url -a "$_name" $_uri
	fi

	cvw_say -o "$_slug"
}


function gogs_remove
{
	cvw_service -z $_slug
	cvw_backup -z $_slug
	cvw_mysql -z $_slug $_slug

	if id gogs >/dev/null 2>&1 ; then
		cvw_say -h "Removing Gogs"
		userdel -fr gogs 2>/tmp/cvw/error
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				gogs_install
			else
				gogs_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

