#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_bitnami - Install or remove Bitnami
######               https://bitnami.com/stack/lamp
######               https://docs.bitnami.com/installer/infrastructure/lamp/#add-applications-amp
######               https://bitnami.com/stack/lamp/modules
######               https://docs.bitnami.com/installer/infrastructure/ruby/
######               https://bitnami.com/stack/ruby/modules
######
###### (c) 2016-2017 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Bitnami"
_slug="bitnami"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function bitnami_install
{
	cvw_say -h "Installing $_name"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _port=$(cvw_xml -r software/$_slug/port)
	local _ssl_port=$(cvw_xml -r software/$_slug/ssl_port)
	local _lang=$(cvw_xml -r system/language)
	local _user=$(cvw_xml -r users/rootmail)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _mode="lamp"
	local _run _file _cert

	cvw_xml -t software/$_slug/ruby && _mode="ruby"
	cvw_download -i ${_slug}_$_mode $_root/Download
	_run=$(cvw_download -f ${_slug}_$_mode)
	chmod +x $_root/Download/$_run
	cvw_rpm -i perl-Data-Dumper

	_file=$_root/Download/$_mode.options
	cat >$_file.tmp_VW <<-EOF
		installer-language=${_lang%_*}
		prefix=$_root/app
		base_user=$_user
		base_user_name=$(cvw_xml -r users/user:$_user/info)
		base_mail=$_user@${_fqdn#*.}
		base_password=$(cvw_xml -r users/user:$_user/password)
		apache_server_port=$_port
		apache_server_ssl_port=$_ssl_port
		web_server_domain=$_fqdn
		mysql_password=$(cvw_xml -r software/$_slug/password/mysql)
		mysql_database_name=dummy
		mysql_database_username=dummy
		mysql_database_password=$(cvw_xml -r users/user:$_user/password)
		phpmyadmin_password=$(cvw_xml -r software/$_slug/password/phpmyadmin)
		launch_cloud=0
	EOF
	if [[ $_mode == "ruby" ]] ; then
		cat >>$_file.tmp_VW <<-EOF
			enable-components=subversion,mysql,php,varnish,nodejs,redis,phpmyadmin,memcached
			disable-components=postgres,Sphinx,phppgadmin,nginx,git,rvm,samplerails
			rubystackinstalltype=standard
		EOF
	fi
	[[ -s /tmp/cvw/error ]] && exit 1
	cvw_file -v $_file bitnami:apache bitnami:mysql

	if [[ ! -s $_root/app/uninstall.dat ]] ; then
		cvw_say -s "running $_run"
		$_root/Download/$_run --mode unattended --optionfile $_file 2>>/tmp/cvw/error
	fi
	ln -nfs $_root/app/ctlscript.sh /usr/local/bin/ctlscript.sh

	if cvw_xml -a software/certbot ; then
		_cert="/etc/letsencrypt/live/$_fqdn"
		for _file in privkey.pem server.csr ; do
			rm -f $_root/app/apache2/conf/$_file
		done
		cp $_cert/privkey.pem $_root/app/apache2/conf/server.key.tmp_VW
		cvw_file -v $_root/app/apache2/conf/server.key bitnami:apache
		cp $_cert/cert.pem $_root/app/apache2/conf/server.crt.tmp_VW
		cvw_file -v $_root/app/apache2/conf/server.crt bitnami:apache
	fi

	if cvw_xml -t software/$_slug/public ; then
		cvw_firewall -t $_port
		cvw_firewall -t $_ssl_port
	fi

	cvw_say -o "$_slug"
}


function bitnami_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	if [[ -s $_root/app/.bitnamirc ]] ; then
		cvw_say -h "Removing $_name"

		rm -rf $_root
		rm -f /usr/local/bin/ctlscript.sh

		cvw_say -o "$_slug:remove"
	fi
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				bitnami_install
			else
				bitnami_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

