#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_dadamail - Install or remove Dada Mail
######                http://dadamailproject.com/
######                http://dadamailproject.com/support/documentation-10_7_1/install_dada_mail_cl.pod.html
######
###### (c) 2016-2017 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Dada Mail"
_slug="dadamail"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		    or: $_prog -g   Generate config template
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function dadamail_template
{
	local _fqdn=$(cvw_xml -r host/fqdn)

	cat <<-EOF
	    <dadamail active="true">
	      <uri>/news</uri>
	      <password>$(cvw -p 20)</password>
	      <admin>
	        <name>newsadmin</name>
	        <password>$(cvw -p 20)</password>
	        <email>newsadmin@${_fqdn#*.}</email>
	      </admin>
	    </dadamail>

	EOF
	exit 0
}


function dadamail_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	local _adm_name=$(cvw_xml -r software/$_slug/admin/name)
	local _adm_pass=$(cvw_xml -r software/$_slug/admin/password)
	local _adm_mail=$(cvw_xml -r software/$_slug/admin/email)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _perl

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      Admin User ..............: $_adm_name
			      Admin Password ..........: $_adm_pass
			      Admin Email .............: $_adm_mail
		EOF
	fi
	[[ -s /tmp/cvw/error ]] && exit 1

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci
	cvw_backup -m $_slug -u $_slug -p $_pass $_slug $_root/app

	cvw_unpack -i $_slug $_root/app mail.cgi

	cvw_rpm -i gcc
	cvw_rpm -i perl-GD
	cvw_rpm -i libxml2-devel
	curl -fsL http://cpanmin.us | perl - --self-upgrade
	for _perl in \
		Bundle::DadaMail
	do
		cvw_say -a "PERL install $_perl"
		cpanm --quiet $_perl 2>>/tmp/cvw/error
	done

	mkdir -p $_root/static

	if [[ -d $_root/app/installer-disabled ]] ; then
		mv $_root/app/installer-disabled $_root/app/install
		pushd $_root/app/install >/dev/null
		chmod 755 install.cgi
		./install.cgi --program_url https://$_fqdn$_uri/mail.cgi \
				--dada_root_pass $(cvw_xml -r software/$_slug/admin/password) \
				--dada_files_loc $_root/app \
				--support_files_dir_path $_root/static \
				--support_files_dir_url https://$_fqdn/static \
				--backend mysql \
				--sql_server localhost \
				--sql_port 3306 \
				--sql_database $_slug \
				--sql_username $_slug \
				--sql_password $_pass \
				--install_plugins mailing_monitor \
				--install_plugins change_root_password \
				--install_plugins screen_cache \
				--install_plugins log_viewer \
				--install_plugins tracker \
				--install_plugins multiple_subscribe \
				--install_plugins blog_index \
				--install_plugins change_list_shortname \
				--install_wysiwyg_editors ckeditor \
				--wysiwyg_editor_install_ckeditor \
				--wysiwyg_editor_install_tiny_mce \
				--file_browser kcfinder
		popd >/dev/null
		rm -rf $_root/install
		mv $_root/app/install $_root/install
	fi

	# /bin/curl -s --get --url https://mail.railduino.de/news/mail.cgi/_sched56E72160DD28CB9B/_all/_all/_silent/

	chown -R apache $_root/app $_root/static

if false ; then
	if [[ -d /var/local/backup/$_slug/last/mysql && \
	      -d /var/local/backup/$_slug/last/dirs  && \
	      -x /usr/local/bin/bkup.$_slug          && \
	      -x /usr/local/bin/rstr.$_slug ]] ; then
		cvw_say -s "updating / syncing backup"
		/usr/local/bin/bkup.$_slug
	fi
fi

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cat >/tmp/cvw/apache.block <<-EOF

			   AddHandler cgi-script cgi pl
			   Alias $_uri $_root/app
			   <Directory $_root/app>
			      AllowOverride All
			      Options ExecCGI Includes FollowSymlinks
			      Require all granted
			      <IfModule mod_passenger.c>
			         PassengerEnabled off
			      </IfModule>
			   </Directory>
			   Alias /static $_root/static
			   <Directory $_root/static>
			      Require all granted
			   </Directory>
		EOF
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function dadamail_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		cvw_backup -z $_slug
		cvw_mysql -z $_slug $_slug
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":ig" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				dadamail_install
			else
				dadamail_remove
			fi
			exit 0
		;;

		g)
			dadamail_template
			exit 0
		;;
		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

