#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_cmsimple - Install or remove CMSimple CMS
######                https://www.cmsimple.org/en/
######                https://www.cmsimple.org/doku/?Installation
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="CMSimple CMS"
_slug="cmsimple"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function cmsimple_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/php || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _lang=$(cvw_xml -r system/language)
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	local _fqdn=$(cvw_xml -r host/fqdn)
	#local _adm_name=$(cvw_xml -r software/$_slug/admin/name)
	#local _adm_pass=$(cvw_xml -r software/$_slug/admin/password)
	#local _adm_mail=$(cvw_xml -r software/$_slug/admin/email)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _file _subdir

if false ; then
	cvw_say -a "Admin Login URL .........: $(cvw_url -r $_uri)$_slug/"
	cvw_say -a "Admin User ..............: $_adm_name"
	cvw_say -a "Admin Password ..........: $_adm_pass"
	cvw_say -a "Admin Email .............: $_adm_mail"
fi

	cvw_unpack -i $_slug $_root/app index.php
	for _subdir in 2author 2lang 2site 2site2lang ; do
		if [[ -d $_root/app/$_subdir ]] ; then
			rm -rf $_root/$_subdir
			mv $_root/app/$_subdir $_root/$_subdir
		fi
	done
	for _subdir in content userfiles cmsimple/languages templates ; do
		mkdir -p $_root/app/$_subdir
		chown -R apache $_root/app/$_subdir
	done
	for _file in disabled_plugins.txt cmsimple/config.php cmsimple/log.txt ; do
		touch $_root/app/$_file
		chown apache $_root/app/$_file
	done

if false ; then
	_file=$_root/app/.htaccess
	if [[ ! -r $_file ]] ; then
		cp $_root/app/htaccess.txt $_file.tmp_VW
		cvw_file -v $_file $(cvw_php -s)
	fi
	if [[ "$_uri" == "/" ]] ; then
		cvw_file -e $_file "s|^ \( RewriteBase\).*|  #\1 /pw/|" $(cvw_php -s)
	else
		cvw_file -e $_file "s|# \(RewriteBase /pw/\)|\1|" $(cvw_php -s)
		cvw_file -e $_file "s|^\(  RewriteBase\).*|\1 $_uri/|" $(cvw_php -s)
	fi

	_file="/etc/profile.d/alias_$_slug.sh"
	cat >$_file.tmp_VW <<-EOF
		#
		# shell aliases for cmsimple
		#

		alias pw-p='cd /var/local/cmsimple/app'
		alias pw-w='cd /var/local/cmsimple/app/wire'
		alias pw-s='cd /var/local/cmsimple/app/site'
		alias pw-a='cd /var/local/cmsimple/app/site/assets'
		alias pw-m='cd /var/local/cmsimple/app/site/modules'
		alias pw-t='cd /var/local/cmsimple/app/site/templates'
	EOF
	cvw_file -v $_file

	_file=$_root/app/site/config.php
	if grep -q -s $_pass $_file ; then
		chmod 0400 $_file
		chown -R root   $_root/app
		chown -R apache $_root/app/site
	else
		cvw_say -a "waiting for install .....: https://$_fqdn${_uri%/}/install.php"
		chown -R apache $_root/app
	fi
fi

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function cmsimple_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		cvw_mysql -z $_slug $_slug
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				cmsimple_install
			else
				cmsimple_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

