#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_borgbackup - Install or remove BorgBackup
######                  https://www.borgbackup.org/
######                  https://borgbackup.readthedocs.io/en/stable/installation.html
######                  https://thomas-leister.de/server-backups-mit-borg/
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="BorgBackup"
_slug="borgbackup"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		    or: $_prog -g   Generate config template
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function borgbackup_generate
{
	cat <<-EOF
	    <borgbackup active="true">
	      <server>server:port</server>
	    </borgbackup>

	EOF
	exit 0
}


function borgbackup_install
{
	cvw_say -h "Installing $_name"

	cvw_rpm -i borgbackup

	cvw_say -o "$_slug"
}


function borgbackup_remove
{
	if cvw_rpm -c borgbackup ; then
		cvw_say -h "Removing $_name"

		cvw_rpm -e borgbackup

		cvw_say -o "$_slug:remove"
	fi
}


while getopts ":ig" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				borgbackup_install
			else
				borgbackup_remove
			fi
			exit 0
		;;

		g)
			borgbackup_generate
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

