#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_picocms - Install or remove Pico CMS
######               http://picocms.org/
######               http://picocms.org/docs/#install
######
###### (c) 2017-2018 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Pico CMS"
_slug="picocms"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function picocms_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/php || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _zone=$(cvw_xml -r system/timezone)
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _title=$(cvw_xml -r software/$_slug/title)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _app=$_root/app
	local _theme _tname _file

	if cvw_xml -c software/$_slug/theme ; then
		_theme=$(cvw_xml -r software/$_slug/theme)
		_tname=${_theme##*/}
		_tname=${_tname%.git}
		cvw_git -r $_theme -d $_app/themes/$_tname
	else
		_theme="default"
	fi

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      Site Title ..............: $_title
			      Theme ...................: $_tname
			      Timezone ................: $_zone
		EOF
		[[ -s /tmp/cvw/error ]] && exit 1
	fi

	cvw_unpack -m -s -i $_slug $_app index.php

	_file="$_app/config/config.php"
	cat >$_file.tmp_VW <<-EOF
		<?php
		\$config['site_title'] = '$_title';
		\$config['theme']      = '$_tname';
		\$config['timezone']   = '$_zone';
	EOF
	cvw_file -v $_file $(cvw_php -s)

	_file="/etc/profile.d/alias_$_slug.sh"
	cat >$_file.tmp_VW <<-EOF
		#
		# shell aliases for $_name
		#
		alias pi-a='cd $_app'
		alias pi-c='cd $_app/content'
		alias pi-o='cd $_app/config'
		alias pi-p='cd $_app/plugins'
		alias pi-t='cd $_app/themes'
	EOF
	cvw_file -v $_file

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				picocms_install
			else
				cvw_php -z $_slug
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

