#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_clamav - Install or remove ClamAV
######              https://www.clamav.net/
######              https://www.adminsys.ch/2015/08/21/installing-clamav-epel-centosred-hat-7-nightmare/
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="ClamAV"
_slug="clamav"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function clamav_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/postfix || cvw_say -f "$_prog: requires postfix"
	local _socket=$(cvw_xml -r software/$_slug/socket)
	local _milter=$(cvw_xml -r software/$_slug/milter)
	local _clamd=$(cvw_xml -r software/$_slug/clamd)
	local _file

	cvw_rpm -i clamav

	cvw_rpm -i clamav-update
	_file=/etc/freshclam.conf
	cvw_file -e $_file "s/^\(Example\)/#\1/"

	cvw_rpm -i clamav-scanner-systemd
	cvw_service -s clamd@scan
	_file=/etc/clamd.d/scan.conf
	cvw_file -e $_file "s/^\(Example\)/#\1/" clamd@scan
	cvw_file -e $_file "s/^#\(LocalSocket \)/\1/" clamd@scan
	cvw_file -e $_file "s/^#\(TCPSocket \)/\1/" clamd@scan
	cvw_file -l $_file /etc/clamd.conf

	cvw_rpm -i clamav-milter-systemd
	cvw_service -s clamav-milter
	mkdir -p /etc/mail
	_file=/etc/mail/clamav-milter.conf
	cvw_file -b
	cat >$_file.tmp_VW <<-EOF
		##
		## Config file for clamav-milter
		##
		MilterSocket $_socket
		User clamilt
		AllowSupplementaryGroups yes

		##
		## Clamd options
		##
		ClamdSocket $_clamd
		LocalNet local

		##
		## Actions
		##
		#VirusAction /usr/local/bin/my_infected_message_handler

		##
		## Logging options
		##
		LogSyslog yes
		LogFacility LOG_MAIL
	EOF
	cvw_file -v $_file clamav-milter

	echo "30 $_milter" >>/tmp/cvw/postfix.milters

	cvw_say -o "$_slug"
}


function clamav_remove
{
	local _file

	if cvw_rpm -c clamav ; then
		cvw_say -h "Removing $_name"
		cvw_rpm -e clamav-update
		cvw_rpm -e clamav-scanner-systemd
		cvw_rpm -e clamav
		rm -rf /etc/clamd.d /etc/clamd.conf /etc/freshclam.conf
		cvw_say -o "$_slug:remove"
	fi
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				clamav_install
			else
				clamav_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

