#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_piwik - Install or remove Piwik analytics
######             http://piwik.org/
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Piwik analytics"
_slug="piwik"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function piwik_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _conf _file _subdir _dest

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci

	cvw_unpack -i $_slug $_root/app index.php
	for _subdir in config tmp ; do
		mkdir -p $_root/app/$_subdir
	done
	for _subdir in plugins/Morpheus/icons/submodules ; do
		if [[ -d $_root/app/$_subdir ]] ; then
			cvw_say -s "hiding $_root/app/$_subdir"
			rm -rf $_root/$_subdir
			mv $_root/app/$_subdir $_root
		fi
	done
	chown -R apache $_root/app

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_backup -m $_slug -u $_slug -p $_pass $_slug $_root/app
	cvw_borgclient -m $_slug
	cvw_borgclient -d $_root/app

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function piwik_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		cvw_mysql -z $_slug $_slug
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				piwik_install
			else
				piwik_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

