#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_oscommerce - Install or remove osCommerce
######                  https://www.oscommerce.com/
######
###### (c) 2016-2020 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="osCommerce Shop"
_slug="oscommerce"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function oscommerce_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	local _md5=$(cvw_xml -r software/$_slug/md5)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _conf _file _check _subdir _dist

	cvw_backup -m $_slug -u $_slug -p $_pass $_slug \
		$_root/root

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci

	_file="/var/local/cvw/files/oscommerce-2.3.4.zip"
	_check=$(md5sum $_file | cut -c1-32)
	if [[ $_check != $_md5 ]] ; then
		cvw_say -f "oscommerce-2.3.4.zip checksum mismatch"
	fi
	cvw_unpack -f $_file -u apache $_root/download README.md
	if [[ ! -d $_root/app ]] ; then
		cvw_say -s "moving download/catalog --> app"
		mv $_root/download/catalog $_root/app
	fi

	if [[ -s $_root/app/includes/configure.php ]] ; then
		cvw_say -s "hiding install directory"
		rm -rf $_root/install # just in case
		mv $_root/app/install $_root/install
	fi

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				oscommerce_install
			else
				cvw_php -z $_slug
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

