#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_b2evolution - Install or remove b2evolution CMS
######                   http://b2evolution.net/
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="b2evolution CMS"
_slug="b2evolution"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function b2evolution_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	local _mail=$(cvw_xml -r software/$_slug/email)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _app=$_root/app
	local _conf _file _subdir _dest

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      Installer URL ...........: https://$_fqdn${_uri%/}/install/index.php
			      DB Name / User ..........: $_slug
			      DB Pass .................: $_pass
			      Base URL ................: https://$_fqdn$_uri
			      Admin E-Mail ............: $_mail
		EOF
		[[ -s /tmp/cvw/error ]] && exit 1
	fi

	cvw_backup -m $_slug -u $_slug -p $_pass $_slug \
		$_app/conf \
		$_app/media \
		$_app/plugins

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci

	cvw_unpack -i $_slug $_app index.php
	for _subdir in _cache media ; do
		mkdir -p $_app/$_subdir
		chown -R apache $_app/$_subdir
	done

	_subdir="/var/lib/cvw_cfg/files/b2evolution/skins"

	if [[ -d $_subdir ]] ; then
		find $_subdir -name "*.zip" -print | while read _file ; do
			cvw_say -s "found skin ${_file##*/}"
			unzip -q -u -o -d $_app/skins $_file
		done
	fi

	find $_app -name sample.htaccess -print | while read _file ; do
		_dest="${_file%sample.htaccess}.htaccess"
		if [[ ! -s $_dest ]] ; then
			cp $_file $_dest.tmp_VW
			cvw_file -v $_dest $(cvw_php -s)
		fi
	done

	_file=$_app/conf/_basic_config.php
	if [[ -s $_file ]] ; then
		chown root $_app/conf
		if [[ -d $_app/install ]] ; then
			cvw_say -s "hiding install directory"
			mkdir -p $_root 2>>/tmp/cvw/error
			rm -rf $_root/install # just in case
			mv $_app/install $_root/install
		fi
	else
		cvw_say -a "waiting for installation"
		chown apache $_app/conf
	fi
	cvw_file -v $_file -u root $(cvw_php -s)

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				b2evolution_install
			else
				cvw_php -z $_slug
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

