#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_opencart - Install or remove OpenCart
######                http://www.opencart.com/index.php?route=common/home
######
###### (c) 2017 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="OpenCart Shop"
_slug="opencart"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function opencart_install_native
{
	cvw_say -h "Installing $_name (native)"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	local _fqdn=$(cvw_xml -r host/fqdn)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _conf _file _check _subdir _dist

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci
	cvw_backup -m $_slug -u $_slug -p $_pass $_slug

	cvw_unpack -m -s -i $_slug $_root/download README.md
	if [[ ! -d $_root/app ]] ; then
		cvw_say -s "moving upload --> app"
		mv $_root/download/upload $_root/app 2>>/tmp/cvw/error
	fi
	cvw_unpack -i vqmod $_root/app/vqmod vqmod.php
	chown -R apache:apache $_root/app

	if ! grep -q "VQMod::bootup" $_root/app/admin/index.php ; then
		cvw_say -a "please run https://$_fqdn${_uri%/}/vqmod/install/"
	elif [[ -f $_root/app/config-dist.php ]] ; then
		mv $_root/app/config-dist.php $_root/app/config.php
		mv $_root/app/admin/config-dist.php $_root/app/admin/config.php
		cvw_say -s "waiting for install: https://$_fqdn${_uri%/}/install"
	else
		if [[ -s $_root/app/config.php ]] ; then
			cvw_say -s "hiding install directory"
			rm -rf $_root/install # just in case
			mv $_root/app/install $_root/install
			chown -R root:root $_root/install
		else
			cvw_say -s "waiting for install: https://$_fqdn${_uri%/}/install"
		fi
	fi

if false ; then
	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci
	cvw_backup -m $_slug -u $_slug -p $_pass $_slug $_root \
			$_root/app/image \
			$_root/app/system/storage \
			$_root/app/vqmod

	cvw_unpack -m -s -u apache -i $_slug $_root/download README.md
	if [[ ! -d $_root/app ]] ; then
		cvw_say -s "moving upload --> app"
		mv $_root/download/upload $_root/app 2>>/tmp/cvw/error
	fi
	cvw_unpack -i vqmod $_root/app/vqmod vqmod.php

	if [[ ! -s $_root/app/config.php ]] ; then
		cvw_say -s "running cli_install.php"
		pushd $_root/app/install >/dev/null
		php cli_install.php install \
				--db_hostname localhost \
				--db_username $_slug \
				--db_password $_pass \
				--db_database $_slug \
				--db_driver   mysqli \
				--db_port     3306 \
				--username    $(cvw_xml -r software/$_slug/admin/name) \
				--password    $(cvw_xml -r software/$_slug/admin/password) \
				--email       $(cvw_xml -r software/$_slug/admin/email) \
				--http_server https://$_fqdn$_uri \
				>/tmp/cvw/opencart.result 2>&1
		popd >/dev/null

		if ! grep -q -s SUCCESS /tmp/cvw/opencart.result ; then
			cat /tmp/cvw/opencart.result >>/tmp/cvw/error
			exit 1
		fi
	elif [[ -d $_root/app/install ]] ; then
		cvw_say -s "hiding install directory"
		rm -rf $_root/install # just in case
		mv $_root/app/install $_root/install
	fi

	if [[ -s $_root/app/.htaccess.txt ]] ; then
		cvw_say -s "activating .htaccess"
		mv $_root/app/.htaccess.txt $_root/app/.htaccess
	fi

	if [[ -r /root/.$_slug ]] ; then
		chown -R apache:apache $_root/app
		cvw_say -e "$_slug open for update - be careful"
	elif grep -q "VQMod::bootup" $_root/app/admin/index.php ; then
		if [[ -d $_root/app/vqmod/install ]] ; then
			cvw_say -s "hiding vqmod/install directory"
			rm -rf $_root/vqmod.install # just in case
			mv $_root/app/vqmod/install $_root/vqmod.install
		fi
		chown -R root:root $_root/app
		chown -R apache $_root/app/image
		chown -R apache $_root/app/system/storage
		chown -R apache $_root/app/vqmod
		cvw_say -s "running in production"
	else
		chown -R apache:apache $_root/app
		cvw_say -a "please run https://$_fqdn${_uri%/}/vqmod/install/"
	fi

	if [[ -d /var/local/backup/$_slug/last/mysql && \
	      -d /var/local/backup/$_slug/last/dirs  && \
	      -x /usr/local/bin/bkup.$_slug          && \
	      -x /usr/local/bin/rstr.$_slug ]] ; then
		cvw_say -s "updating / syncing backup"
		/usr/local/bin/bkup.$_slug
	fi
fi

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri
	cvw_url -a "$_name" ${_uri%/}/admin/

	cvw_say -o "$_slug"
}


function opencart_install_bitnami
{
	cvw_say -h "Installing $_name (Bitnami)"
	cvw_xml -a software/bitnami || cvw_say -f "$_prog: requires bitnami"
	local _root=$(cvw_xml -r system/app_root)/bitnami
	local _lang=$(cvw_xml -r system/language)
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _user=$(cvw_xml -r users/rootmail)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _run _file

	cvw_download -i bitnami_$_slug $_root/Download
	_run=$(cvw_download -f bitnami_$_slug)
	chmod +x $_root/Download/$_run

	_file=$_root/Download/$_slug.options
	cat >$_file.tmp_VW <<-EOF
		installer-language=${_lang%_*}
		prefix=$_root/app
		base_user=$_user
		base_user_name=$(cvw_xml -r users/user:$_user/info)
		base_mail=$_user@${_fqdn#*.}
		base_password=$(cvw_xml -r users/user:$_user/password)
		opencart_domain=$_fqdn
		smtp_enable=0
		launch_cloud=0
	EOF
	[[ -s /tmp/cvw/error ]] && exit 1
	cvw_file -v $_file bitnami:apache bitnami:mysql

	if [[ ! -d $_root/app/apps/$_slug ]] ; then
		cvw_say -s "running $_run"
		$_root/Download/$_run --mode unattended --optionfile $_file 2>>/tmp/cvw/error
	fi

	cvw_say -o "$_slug"
}


function opencart_remove_native
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	cvw_backup -z $_slug
	cvw_mysql -z $_slug $_slug
	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name (native)"
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


function opencart_remove_bitnami
{
	local _root=$(cvw_xml -r system/app_root)/bitnami
	local _file=$_root/app/apps/$_slug/uninstall

	if [[ -x $_file ]] ; then
		cvw_say -h "Removing $_name (Bitnami)"
		
		cvw_say -s "running $_file"
		$_file --mode unattended

		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				if cvw_xml -t software/$_slug/bitnami ; then
					opencart_install_bitnami
				else
					opencart_install_native
				fi
			else
				if cvw_xml -t software/$_slug/bitnami ; then
					opencart_remove_bitnami
				else
					opencart_remove_native
				fi
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

