#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_volume - Configure cloud volume
######              This is specific for Hetzner
######              https://console.hetzner.cloud/projects
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Hetzner Cloud Volume"
_slug="volume"

_fstab="/etc/fstab"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i       Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function volume_install
{
	cvw_say -h "Installing $_name"
	local _id="$1"
	local _base="system/$_slug:$_id"
	local _disk=$(cvw_xml -r $_base/disk_id)
	local _path=$(cvw_xml -r $_base/mountpoint)
	local _opts=$(cvw_xml -r $_base/options)
	[[ -s /tmp/cvw/error ]] && exit 1

	mkdir -p $_path

	if ! grep -q $_path $_fstab ; then
		cvw_say -s "mounting $_path"

		rm -rf $_fstab.tmp_VW
		grep -v "$_disk" $_fstab >$_fstab.tmp_VW
		echo "$_disk $_path ext4 $_opts 0 0" >>$_fstab.tmp_VW
		cvw_file -v $_fstab
	fi

	cvw_say -o "$_slug"
}


while getopts ":i" opt ; do
	case $opt in
		i)
			cvw_xml -i system/$_slug | sort | while read _id ; do
				volume_install $_id
			done
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

mount -a

usage

