#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_gitolite - Install or remove Gitolite
######                http://gitolite.com/gitolite/install.html
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Gitolite"
_slug="gitolite"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function gitolite_install
{
	cvw_say -h "Installing $_name"
	local _admin=$(cvw_xml -r software/$_slug/admin)
	[[ -s /tmp/cvw/error ]] && exit 1
	cvw_user -s gitolite
	local _home=$(cvw_user -h gitolite)
	local _file

	cvw_git -i gitolite -d $_home/gitolite
	mkdir -p $_home/bin
	chown -R gitolite:gitolite $_home

	if [[ ! -h $_home/bin/gitolite ]] ; then
		cvw_user -r gitolite "$_home/gitolite/install -ln $_home/bin"
	fi

	if [[ ! -d $_home/repositories ]] ; then
		cp /var/lib/cvw_cfg/files/keys/$_admin.pub $_home 2>>/tmp/cvw/error
		cvw_user -r gitolite "$_home/bin/gitolite setup -pk $_admin.pub"
		rm -f $_home/$_admin.pub
	fi

	cvw_say -o "$_slug"
}


function gitolite_remove
{
	if id gitolite >/dev/null 2>&1 ; then
		cvw_say -h "Removing $_name"
		cvw_user -z gitolite
		cvw_say -o "$_slug:remove"
	fi
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				gitolite_install
			else
				gitolite_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

