#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_piwigo - Install or remove Piwigo gallery
######              http://www.piwigo.org/
######
###### (c) 2016 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Piwigo gallery"
_slug="piwigo"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function piwigo_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _html
	[[ $_uri == "/" ]] && _html="/var/www/html" || _html="$_root$_uri"
	local _conf _home

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci
	cvw_backup -m $_slug -u $_slug -p $_pass $_slug \
			$_html/_data \
			$_html/local \
			$_html/upload

	cvw_unpack -i $_slug $_html index.php
	install -m 0775 -d $_html/upload
	chgrp -R apache $_html/_data \
			$_html/local \
			$_html/upload

	if [[ -d /var/local/backup/$_slug/last/mysql && \
	      -d /var/local/backup/$_slug/last/dirs  && \
	      -x /usr/local/bin/bkup.$_slug          && \
	      -x /usr/local/bin/rstr.$_slug ]] ; then
		cvw_say -s "updating / syncing backup"
		/usr/local/bin/bkup.$_slug
	fi

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p software/$_slug
	fi

	if cvw_xml -a software/apache ; then
		_conf="/etc/httpd/conf.d/vhost.conf.tmp_VW"
		_home=$(cat /tmp/cvw/apache.home)
		[[ -s $_conf ]] || cvw_say -f "$_prog: missing $_conf"
		echo "" >>$_conf
		if [[ $_uri == "/" ]] ; then
			if [[ $_home != $_slug ]] ; then
				cvw_say -f "apache wants $_home as root"
			fi
		else
			if [[ $_home == $_slug ]] ; then
				cvw_say -f "apache wants $_slug as root"
			fi
			echo "   Alias $_uri $_html" >>$_conf
		fi
		cat >>$_conf <<-EOF
			   <Directory $_html>
			      AllowOverride All
			      Require all granted
			   </Directory>
		EOF
		cvw_url -a "$_name" $_uri
	fi

	cvw_say -o "$_slug"
}


function piwigo_remove
{
	local _web=$(cvw_xml -r system/web/server)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _html
	[[ $_uri == "/" ]] && _html="/var/www/html" || _html="$_root$_uri"

	cvw_backup -z $_slug
	cvw_mysql -z $_slug $_slug
	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		if [[ $_web == "apache" && $_uri == "/" ]] ; then
			rm -rf /var/www/html
			mkdir -p /var/www/html
		fi
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				piwigo_install
			else
				piwigo_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

