#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_sqlbuddy - Install or remove SQL Buddy
######                http://sqlbuddy.com/
######
###### (c) 2016 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="SQL Buddy"
_slug="sqlbuddy"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function sqlbuddy_install
{
	cvw_say -h "installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _conf

	cvw_unpack -i $_slug $_root/app index.php

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		_conf=$(cvw_apache -c)
		cat >>$_conf.tmp_VW <<-EOF

			   Alias $_uri $_root/app
			   <Directory $_root/app>
			      Options Indexes FollowSymLinks MultiViews
			      <IfModule mod_passenger.c>
			         PassengerEnabled off
			      </IfModule>
			      AllowOverride none
			      Require all granted
			   </Directory>
		EOF
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function sqlbuddy_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)

	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				sqlbuddy_install
			else
				sqlbuddy_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

