#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_squirrelmail - Install or remove SquirrelMail
######
###### (c) 2016 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
######          TODO add nginx support for SquirrelMail
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove SquirrelMail
		Called with: '$_prog $_args'
	EOF

	if [ -d /tmp/cvw ] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function init_squirrelmail
{
	cvw_say -h "Installing SquirrelMail"
	cvw_xml -a software/apache || cvw_say -f "$_prog: requires apache"
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _lang=$(cvw_xml -r system/language)
	local _domain=${_fqdn#*.}
	test -s /tmp/cvw/error && exit 1
	local _http="/etc/httpd/conf.d/squirrelmail.conf"
	local _conf="/etc/squirrelmail/config_local.php"
	local _diff _vhost _uri

	if [ ! -s $_http ] ; then
		cvw_service -r httpd
	fi

	cvw_rpm -i squirrelmail
	cvw_apache -e squirrelmail

	cvw_file -b $_http
	if ! grep -q passenger $_http ; then
		_diff="/var/local/cfg/files/diffs/squirrelmail.diff"
		patch -d /etc/httpd/conf.d -i $_diff 2>/tmp/cvw/error
	fi

	_uri=$(awk -e '/^Alias/ { print $2 }' $_http)
	cvw_xml -i software/apache/vhost | sort | while read _vhost ; do
		cvw_url -a "SquirrelMail" $_uri
	done

	cvw_file -b $_conf
	cat >$_conf.tmp_VW <<-EOF
		<?php

		/**
		 * Local config overrides.
		 *
		 * You can override the config.php settings here.
		 * Don't do it unless you know what you're doing.
		 * Use standard PHP syntax, see config.php for examples.
		 *
		 * @copyright &copy; 2002-2006 The SquirrelMail Project Team
		 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
		 * @version \$Id\$
		 * @package squirrelmail
		 * @subpackage config
		 */

		\$config_version                = '$(rpm -q --qf="%{VERSION}" squirrelmail)';
		\$squirrelmail_default_language = '$_lang';
		\$domain                        = '$_domain';
		\$imap_server_type              = 'dovecot';
		\$default_folder_prefix         = '';
		?>
	EOF
	test -s /tmp/cvw/error && exit 1
	cvw_file -v $_conf httpd

	cvw_say -o "squirrelmail"
}


function remove_squirrelmail
{
	set +e
	local _http="/etc/httpd/conf.d/squirrelmail.conf"
	local _conf="/etc/squirrelmail/config_local.php"

	if cvw_rpm -c squirrelmail ; then
		cvw_say -h "Removing SquirrelMail"
		cvw_rpm -e squirrelmail
		rm -f $_http $_http.rpmsave
		rm -f $_conf $_conf.rpmsave
		cvw_say -o "squirrelmail:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/squirrelmail ; then
				init_squirrelmail
			else
				remove_squirrelmail
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

