#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_yellow - Install or remove Datenstrom Yellow CMS
######              https://datenstrom.se/yellow/
######              https://developers.datenstrom.se/help/how-to-make-a-website
######
###### (c) 2018 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Datenstrom Yellow CMS"
_slug="yellow"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function yellow_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/php || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _adm_name=$(cvw_xml -r software/$_slug/admin/name)
	local _adm_mail=$(cvw_xml -r software/$_slug/admin/email)
	local _adm_pass=$(cvw_xml -r software/$_slug/admin/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _phar _file _subdir

	cvw_say -s "Admin name ..............: $_adm_name"
	cvw_say -s "Admin email .............: $_adm_mail"
	cvw_say -s "Admin password ..........: $_adm_pass"

if false ; then
	cvw_backup -m $_slug -u $_slug -p $_pass $_slug $_root/app
fi

	cvw_unpack -u apache -i $_slug $_root/app yellow.php

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function yellow_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		cvw_backup -z $_slug
		cvw_mysql -z $_slug $_slug
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				yellow_install
			else
				yellow_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

