#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_shariff - Install or remove Heise Shariff
######               https://github.com/heiseonline/shariff-backend-php
######
###### (c) 2016 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Heise Shariff"
_slug="shariff"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function shariff_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/php || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _file

	cvw_unpack -i $_slug $_root index.php

	_file=$_root/build/shariff.json
	cvw_file -b $_file
	cat >$_file.tmp_VW <<-EOF
		{
		  "cache": {
		    "ttl": 60
		  },
		  "domain": "$(cvw_xml -r host/fqdn)",
		  "services": [
		    "Facebook"
		  ]
		}
	EOF
	cvw_file -v $_file httpd nginx php-fpm

	cvw_say -o "$_slug"
}


function shariff_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				shariff_install
			else
				shariff_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

