#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_davical - Install or remove DAViCal
######               https://www.davical.org/
######               https://www.davical.org/installation.php
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="DAViCal"
_slug="davical"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		    or: $_prog -g   Generate config template
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function davical_generate
{
	cat <<-EOF
	    <davical active="true">
	      <uri>/davical</uri>
	      <password>$(cvw -p 20)</password>
	    </davical>

	EOF
	exit 0
}


function davical_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/postgresql || cvw_say -f "$_prog: requires postgresql"
	cvw_xml -a software/php        || cvw_say -f "$_prog: requires php"
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _file

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      DB Name / User ..........: $_slug
			      DB Pass .................: $_pass
			      Base URL ................: https://$_fqdn$_uri
		EOF
		[[ -s /tmp/cvw/error ]] && exit 1
	fi

	cvw_postgresql -u $_slug $_pass

	cvw_unpack -i $_slug       $_root/app/davical index.php
	cvw_unpack -i ${_slug}_awl $_root/awl/dba phpdoc.ini

	if [ ! -h /usr/share/awl ] ; then
		ln -s $_root/awl /usr/share/awl
	fi

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


while getopts ":ig" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				davical_install
			else
				cvw_php -z $_slug
			fi
			exit 0
		;;

		g)
			davical_generate
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

