#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_b2evolution - Install or remove b2evolution CMS
######                   http://b2evolution.net/
######
###### (c) 2016 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="b2evolution CMS"
_slug="b2evolution"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function b2evolution_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _conf _file _subdir _dest

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci
	cvw_backup -m $_slug -u $_slug -p $_pass $_slug \
			$_root/app/conf \
			$_root/app/media \
			$_root/app/plugins

	cvw_unpack -i $_slug $_root/app index.php
	for _subdir in _cache media ; do
		mkdir -p $_root/app/$_subdir
		chown -R apache $_root/app/$_subdir
	done

	if [[ -d /var/local/backup/$_slug/last/mysql && \
	      -d /var/local/backup/$_slug/last/dirs  && \
	      -x /usr/local/bin/bkup.$_slug          && \
	      -x /usr/local/bin/rstr.$_slug ]] ; then
		cvw_say -s "updating / syncing backup"
		/usr/local/bin/bkup.$_slug
	fi

	find $_root/app -name sample.htaccess -print | while read _file ; do
		_dest="${_file%sample.htaccess}.htaccess"
		if [[ ! -s $_dest ]] ; then
			cp $_file $_dest.tmp_VW
			cvw_file -v $_dest $(cvw_php -s)
		fi
	done

	_file=$_root/app/conf/_basic_config.php
	if [[ -s $_file ]] ; then
		chown root $_root/app/conf
		if [[ -d $_root/app/install ]] ; then
			cvw_say -s "hiding install directory"
			mkdir -p $_root 2>>/tmp/cvw/error
			rm -rf $_root/install # just in case
			mv $_root/app/install $_root/install
		fi
	else
		cvw_say -s "waiting for installation"
		chown apache $_root/app/conf
	fi
	cvw_file -v $_file -u root $(cvw_php -s)

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function b2evolution_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	cvw_backup -z $_slug
	cvw_mysql -z $_slug $_slug
	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				b2evolution_install
			else
				b2evolution_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

