#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_opencart - Install or remove OpenCart
######                http://www.opencart.com/index.php?route=common/home
######
###### (c) 2016 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="OpenCart Shop"
_slug="opencart"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function opencart_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	local _md5=$(cvw_xml -r software/$_slug/md5)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _conf _file _check _subdir _dist

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci
	cvw_backup -m $_slug -u $_slug -p $_pass $_slug \
			$_root/app/image \
			$_root/app/system/storage

	_file="/var/local/cvw/files/OpenCart.tgz"
	_check=$(md5sum $_file | cut -c1-32)
	if [[ $_check != $_md5 ]] ; then
		cvw_say -f "OpenCart.tgz checksum mismatch"
	fi
	cvw_unpack -f $_file -u apache $_root/app index.php

	if [[ -d /var/local/backup/$_slug/last/mysql && \
	      -d /var/local/backup/$_slug/last/dirs  && \
	      -x /usr/local/bin/bkup.$_slug          && \
	      -x /usr/local/bin/rstr.$_slug ]] ; then
		cvw_say -s "updating / syncing backup"
		/usr/local/bin/bkup.$_slug
	fi

	_file=$_root/app/.htaccess
	cat >$_file.tmp_VW <<-EOF
		Options +FollowSymlinks
		Options -Indexes
		<FilesMatch "(?i)((\\.tpl|\\.ini|\\.log|(?<!robots)\\.txt))">
		   Require all denied
		</FilesMatch>

		RewriteEngine On
		RewriteBase ${_uri%/}/
		RewriteRule ^sitemap.xml\$ index.php?route=extension/feed/google_sitemap [L]
		RewriteRule ^googlebase.xml\$ index.php?route=extension/feed/google_base [L]
		RewriteRule ^system/download/(.*) index.php?route=error/not_found [L]
		RewriteCond %{REQUEST_FILENAME} !-f
		RewriteCond %{REQUEST_FILENAME} !-d
		RewriteCond %{REQUEST_URI} !.*\\.(ico|gif|jpg|jpeg|png|js|css)
		RewriteRule ^([^?]*) index.php?_route_=\$1 [L,QSA]
	EOF
	cvw_file -v $_file $(cvw_php -s)
	_file=$_root/app/.htaccess.txt
	[[ -r $_file ]] && mv $_file $_root/htaccess.txt

	_file=$_root/app/config.php
	_dist=$_root/app/config-dist.php
	cat >$_file.tmp_VW <<-EOF
		<?php
		// HTTP
		define('HTTP_SERVER', 'https://$_fqdn${_uri%/}/');

		// HTTPS
		define('HTTPS_SERVER', 'https://$_fqdn${_uri%/}/');

		// DIR
		define('DIR_APPLICATION', '$_root/app/catalog/');
		define('DIR_SYSTEM', '$_root/app/system/');
		define('DIR_IMAGE', '$_root/app/image/');
		define('DIR_LANGUAGE', '$_root/app/catalog/language/');
		define('DIR_TEMPLATE', '$_root/app/catalog/view/theme/');
		define('DIR_CONFIG', '$_root/app/system/config/');
		define('DIR_CACHE', '$_root/app/system/storage/cache/');
		define('DIR_DOWNLOAD', '$_root/app/system/storage/download/');
		define('DIR_LOGS', '$_root/app/system/storage/logs/');
		define('DIR_MODIFICATION', '$_root/app/system/storage/modification/');
		define('DIR_UPLOAD', '$_root/app/system/storage/upload/');

		// DB
		define('DB_DRIVER', 'mysqli');
		define('DB_HOSTNAME', 'localhost');
		define('DB_USERNAME', '$_slug');
		define('DB_PASSWORD', '$_pass');
		define('DB_DATABASE', '$_slug');
		define('DB_PORT', '3306');
		define('DB_PREFIX', 'oc_');
	EOF
	if [[ -s $_file ]] ; then
		cvw_file -v $_file $(cvw_php -s)
		[[ -e $_dist ]] && mv $_dist $_root/config-dist.php
	elif [[ -e $_dist ]] ; then
		# pristine install
		install -o apache -g apache -m 0644 /dev/null $_file
	fi

	_file=$_root/app/admin/config.php
	_dist=$_root/app/admin/config-dist.php
	cat >$_file.tmp_VW <<-EOF
		<?php
		// HTTP
		define('HTTP_SERVER', 'https://$_fqdn${_uri%/}/admin/');
		define('HTTP_CATALOG', 'https://$_fqdn${_uri%/}/');

		// HTTPS
		define('HTTPS_SERVER', 'https://$_fqdn${_uri%/}/admin/');
		define('HTTPS_CATALOG', 'https://$_fqdn${_uri%/}/');

		// DIR
		define('DIR_APPLICATION', '$_root/app/admin/');
		define('DIR_SYSTEM', '$_root/app/system/');
		define('DIR_IMAGE', '$_root/app/image/');
		define('DIR_LANGUAGE', '$_root/app/admin/language/');
		define('DIR_TEMPLATE', '$_root/app/admin/view/template/');
		define('DIR_CONFIG', '$_root/app/system/config/');
		define('DIR_CACHE', '$_root/app/system/storage/cache/');
		define('DIR_DOWNLOAD', '$_root/app/system/storage/download/');
		define('DIR_LOGS', '$_root/app/system/storage/logs/');
		define('DIR_MODIFICATION', '$_root/app/system/storage/modification/');
		define('DIR_UPLOAD', '$_root/app/system/storage/upload/');
		define('DIR_CATALOG', '$_root/app/catalog/');

		// DB
		define('DB_DRIVER', 'mysqli');
		define('DB_HOSTNAME', 'localhost');
		define('DB_USERNAME', '$_slug');
		define('DB_PASSWORD', '$_pass');
		define('DB_DATABASE', '$_slug');
		define('DB_PORT', '3306');
		define('DB_PREFIX', 'oc_');
	EOF
	if [[ -s $_file ]] ; then
		cvw_file -v $_file $(cvw_php -s)
		[[ -e $_dist ]] && mv $_dist $_root/admin-dist.php
		if [[ -d $_root/app/install ]] ; then
			cvw_say -s "hiding install directory"
			rm -rf $_root/install # just in case
			mv $_root/app/install $_root/install
		fi
	elif [[ -e $_dist ]] ; then
		# pristine install
		install -o apache -g apache -m 0644 /dev/null $_file
	fi

	chown -R apache:apache $_root/app

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function opencart_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	cvw_backup -z $_slug
	cvw_mysql -z $_slug $_slug
	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				opencart_install
			else
				opencart_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

