#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_nfs_client - Install or remove NFS client
######                  https://www.howtoforge.com/tutorial/setting-up-an-nfs-server-and-client-on-centos-7/
######
###### (c) 2016-2021 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="NFS Client"
_slug="nfs_client"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function nfs_client_install
{
	cvw_say -h "Installing $_name"
	local _remote _mount

	cvw_rpm -i nfs-utils

	for _id in $(cvw_xml -i system/$_slug/mount) ; do
		_remote=$(cvw_xml -r system/$_slug/mount:$_id/remote)
		_path=$(cvw_xml -r system/$_slug/mount:$_id/path)
		cvw_say -s "mounting $_remote --> $_path"
		install -d $_path

		rm -rf /etc/fstab.tmp_VW
		grep -v "$_path" /etc/fstab >/etc/fstab.tmp_VW
		echo "$_remote $_path nfs rw,sync,soft,intr 0 0" >>/etc/fstab.tmp_VW
		cvw_file -v /etc/fstab

		mount -a
	done

	cvw_say -o "$_slug"
}


function nfs_client_remove
{
	if grep -q nfs /etc/fstab ; then
		cvw_say -h "Please remove $_name manually"
		cvw_say -o "$_slug:remove"
	fi
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a system/$_slug ; then
				nfs_client_install
			else
				nfs_client_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

