#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_web2project - Install or remove Web2project
######                   https://web2project.net/
######                   hhttps://docs.web2project.net/docs/installation.html
######
###### (c) 2016-2020 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Web2project"
_slug="web2project"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function web2project_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	#local _fqdn=$(cvw_xml -r host/fqdn)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	#local _sess=$(cvw_xml -r software/$_slug/session)
	#local _site=$(cvw_xml -r software/$_slug/sitename)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _app=$_root/app
	local _file _subdir

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      DB Name / User ..........: $_slug
			      DB Pass .................: $_pass
		EOF
		[[ -s /tmp/cvw/error ]] && exit 1
	fi

	cvw_backup -m $_slug -u $_slug -p $_pass $_slug

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci

	cvw_unpack -i $_slug $_app index.php
	for _subdir in files locales ; do
		mkdir -p $_app/$_subdir
		chown -R apache $_app/$_subdir
	done

	_file=$_app/includes/config.php
	cat >$_file.tmp_VW <<-EOF
		<?php
		if (!defined('W2P_BASE_DIR')) {
		    die('You should not access this file directly.');
		}

		\$w2Pconfig['dbtype']   = 'mysqli';
		\$w2Pconfig['dbchar']   = 'utf8';
		\$w2Pconfig['dbhost']   = 'localhost';
		\$w2Pconfig['dbname']   = '$_slug';
		\$w2Pconfig['dbuser']   = '$_slug';
		\$w2Pconfig['dbpass']   = '$_pass';
		\$w2Pconfig['dbprefix'] = '';

		// set this value to true to use persistent database connections
		\$w2Pconfig['dbpersist'] = false;

		\$w2Pconfig['root_dir'] = W2P_BASE_DIR;
		\$w2Pconfig['base_url'] = W2P_BASE_URL;
	EOF
	cvw_file -v $_file $(cvw_php -s)

if false ; then
	chmod -R go-w $_app
	for _subdir in archives plugins templates_c uploads spamblock ; do
		mkdir -p $_app/$_subdir
	done

	chown -R apache:apache $_app
fi

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				web2project_install
			else
				cvw_php -z $_slug
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

