#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_mantis - Install or remove Mantis BT
######              http://mantisbt.org/index.php
######              http://mantisbt.org/docs/master/en-US/Admin_Guide/html-single/#admin.install
######
###### (c) 2016-2021 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Mantis BT"
_slug="mantis"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function mantis_template
{
	cat <<-EOF
	    <mantis active="true">
	      <uri>/tracker</uri>
	      <password>$(cvw -p 20)</password>
	      <salt>$(cvw -p 44)</salt>
	      <title>Example Bug Tracker</title>
	    </mantis>

	EOF
	exit 0
}


function mantis_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	local _salt=$(cvw_xml -r software/$_slug/salt)
	local _title=$(cvw_xml -r software/$_slug/title)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _domain=${_fqdn#*.}
	local _conf _file _subdir

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      Username / Database .....: $_slug
			      Password ................: $_pass
		EOF
		[[ -s /tmp/cvw/error ]] && exit 1
	fi

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci

	cvw_unpack -i $_slug $_root/app index.php
	for _subdir in plugins uploads ; do
		mkdir -p $_root/app/$_subdir
	done
	chown -R apache $_root/app

	_file=$_root/app/config/config_inc.php
	cat >$_file.tmp_VW <<-EOF
		<?php

		# --- Database Configuration ---
		\$g_hostname			= 'localhost';
		\$g_db_type			= 'mysqli';
		\$g_database_name		= '$_slug';
		\$g_db_username			= '$_slug';
		\$g_db_password			= '$_pass';
		\$g_default_language		= 'german';
		\$g_default_timezone		= 'Europe/Berlin';

		# --- Security ---
		\$g_crypto_master_salt		= '$_salt';

		# --- Anonymous Access / Signup ---
		\$g_allow_signup			= ON;
		\$g_allow_anonymous_login	= OFF;
		\$g_anonymous_account		= '';

		# --- Email Configuration ---
		\$g_phpMailer_method		= PHPMAILER_METHOD_MAIL;
		\$g_smtp_host			= 'localhost';
		\$g_smtp_username		= '';
		\$g_smtp_password		= '';
		\$g_webmaster_email		= 'webmaster@$_domain';
		\$g_from_email			= 'noreply@$_domain';
		\$g_return_path_email		= 'admin@$_domain';
		\$g_from_name			= '$_title';
		\$g_email_receive_own		= OFF;
		\$g_email_send_using_cronjob	= OFF;

		# --- Attachments / File Uploads ---
		\$g_allow_file_upload		= ON;
		\$g_file_upload_method		= DISK;
		\$g_absolute_path_default_upload_folder = '$_root/app/uploads';
		\$g_max_file_size		= 5000000;
		\$g_preview_attachments_inline_max_size = 256 * 1024;
		# \$g_allowed_files		= '';
		# \$g_disallowed_files		= '';

		# --- Branding ---
		\$g_window_title			= '$_title';
		\$g_logo_image			= 'images/${_slug}_logo.png';
		\$g_favicon_image		= 'images/favicon.ico';

		# --- Real names ---
		\$g_show_realname		= OFF;
		\$g_show_user_realname_threshold	= MANAGER;

		# --- Others ---
		\$g_default_home_page		= 'my_view_page.php';
		\$g_signup_use_captcha		= OFF;
	EOF
	cvw_file -v $_file $(cvw_php -s)

	if [[ $(mysqlshow -u$_slug -p$_pass $_slug | wc -l) -gt 10 ]] ; then
		if [[ -d $_root/app/admin ]] ; then
			cvw_say -s "hiding admin directory"
			rm -rf $_root/admin # just in case
			mv $_root/app/admin $_root/admin
		fi
	else
		cvw_say -a "waiting for install .....: $(cvw_url -r $_uri)admin/install.php"
	fi

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	if [[ -x /usr/local/bin/bb.create ]] ; then
		_bkup="/etc/cron.daily/bkup.$_slug"
		cat >$_bkup.tmp_VW <<-EOF
			#!/bin/bash
			set -e
			cd $_root

			mkdir -p mysqldump
			/usr/bin/mysqldump -u$_slug -p$_pass $_slug >mysqldump/$_slug.sql

			/usr/local/bin/bb.create $_slug app mysqldump
			/usr/local/bin/bb.prune  $_slug
		EOF
		cvw_file -m 0775 -v $_bkup
		ln -nfs $_bkup /usr/local/bin/bkup.$_slug
		rm -f /usr/local/bin/rstr.$_slug
	else
		cvw_backup -m $_slug -u $_slug -p $_pass $_slug $_root/app/plugins $_root/app/uploads
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


while getopts ":igq" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				mantis_install
			else
				cvw_php -z $_slug
			fi
			exit 0
		;;

		g)
			mantis_template
			exit 0
		;;

		q)
			cvw_url -q $_slug
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

