#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_tripwire - Install or remove Tripwire
######                https://github.com/Tripwire/tripwire-open-source
######                https://www.centos.org/docs/2/rhl-rg-en-7.2/ch-tripwire.html
######
###### (c) 2016 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Tripwire"
_slug="tripwire"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function tripwire_install
{
	cvw_say -h "Installing $_name"

	cvw_rpm -i tripwire

	cvw_say -o "$_slug"
}


function tripwire_remove
{
	if cvw_rpm -c tripwire ; then
		cvw_say -h "Removing $_name"

		cvw_rpm -e tripwire

		cvw_say -o "$_slug:remove"
	fi
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a system/$_slug ; then
				tripwire_install
			else
				tripwire_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

