#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_seafile - Install or remove Seafile File Sync and Share
######               https://www.seafile.com/en/home/
######               https://manual.seafile.com/
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Seafile"
_slug="seafile"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		    or: $_prog -g   Generate config template
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function seafile_generate
{
	local _pass=$(cvw -p 20)

	cat <<-EOF
	    <seafile active="true">
	      <port>8082</port>
	      <password>$_pass</password>
	    </seafile>

	EOF
	exit 0
}


function seafile_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	local _addr=$(cvw_xml -r host/addr)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _name=$(cvw_xml -r software/$_slug/name)
	local _port=$(cvw_xml -r software/$_slug/port)
	local _pass=$(cvw_xml -r software/$_slug/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _rpm _db

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      Database Password .......: $_pass
		EOF
	fi

	for _rpm in MySQL-python \
			python-memcached \
			python-ldap \
			python-urllib3 \
			python-requests ; do
		cvw_rpm -i $_rpm
	done

	for _db in ccnet seafile seahub ; do
		cvw_mysql -c $_db $_slug $_pass utf8_general_ci
	done

	cvw_unpack -i $_slug $_root/app seafile.sh
	mkdir -p $_root/data

	pushd $_root/app >/dev/null
	./setup-seafile.sh auto \
			-n $_name -i $_addr -p $_port \
			-d $_root/data \
			-e 1 -u $_slug -w $_pass \
			-c ccnet -s seafile -b seahub
	popd >/dev/null

	cvw_firewall -t $_port

	cvw_say -o "$_slug"
}


function seafile_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		cvw_mysql -z seahub
		cvw_mysql -z seafile
		cvw_mysql -z ccnet $_slug
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":ig" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				seafile_install
			else
				seafile_remove
			fi
			exit 0
		;;

		g)
			seafile_generate
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

