#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_opencart - Install or remove openCart
######                http://www.opencart.com/index.php?route=common/home
######
###### (c) 2016 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="openCart Shop"
_slug="opencart"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function opencart_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _canon=$(cvw_xml -r host/fqdn)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _html
	[[ $_uri == "/" ]] && _html="/var/www/html" || _html="$_root$_uri"
	local _conf _file _subdir _dist

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci
	cvw_backup -m $_slug -u $_slug -p $_pass $_slug \
			$_html/image \
			$_html/system/storage

	_file="/var/local/cvw/files/2.3.0.2-compiled.zip"
	cvw_unpack -f $_file $_html index.php
	for _subdir in phpcs phpmod phpunit setup readme.md ; do
		rm -rf $_html/$_subdir
	done

	_file="/var/local/cvw/files/Translation-German-deDE-Completev.2.0.0-OpenCart-2.x-by-OSWorX.net.ocmod.zip"
	cvw_unpack -f $_file $_html admin/language/de-DE.xml

	for _subdir in image system/storage ; do
		mkdir -p $_html/$_subdir
		chown -R apache $_html/$_subdir
	done

	if [[ -d /var/local/backup/$_slug/last/mysql && \
	      -d /var/local/backup/$_slug/last/dirs  && \
	      -x /usr/local/bin/bkup.$_slug          && \
	      -x /usr/local/bin/rstr.$_slug ]] ; then
		cvw_say -s "updating / syncing backup"
		/usr/local/bin/bkup.$_slug
	fi

	_file=$_html/.htaccess
	cat >$_file.tmp_VW <<-EOF
		Options +FollowSymlinks
		Options -Indexes
		<FilesMatch "(?i)((\\.tpl|\\.ini|\\.log|(?<!robots)\\.txt))">
		   Require all denied
		</FilesMatch>

		RewriteEngine On
		RewriteBase ${_uri%/}/
		RewriteRule ^sitemap.xml\$ index.php?route=extension/feed/google_sitemap [L]
		RewriteRule ^googlebase.xml\$ index.php?route=extension/feed/google_base [L]
		RewriteRule ^system/download/(.*) index.php?route=error/not_found [L]
		RewriteCond %{REQUEST_FILENAME} !-f
		RewriteCond %{REQUEST_FILENAME} !-d
		RewriteCond %{REQUEST_URI} !.*\\.(ico|gif|jpg|jpeg|png|js|css)
		RewriteRule ^([^?]*) index.php?_route_=\$1 [L,QSA]
	EOF
	cvw_file -v $_file $(cvw_php -s)
	_file=$_html/.htaccess.txt
	[[ -r $_file ]] && mv $_file $_root/htaccess.txt

	_file=$_html/config.php
	_dist=$_html/config-dist.php
	cat >$_file.tmp_VW <<-EOF
		<?php
		// HTTP
		define('HTTP_SERVER', 'https://$_canon${_uri%/}/');

		// HTTPS
		define('HTTPS_SERVER', 'https://$_canon${_uri%/}/');

		// DIR
		define('DIR_APPLICATION', '$_html/catalog/');
		define('DIR_SYSTEM', '$_html/system/');
		define('DIR_IMAGE', '$_html/image/');
		define('DIR_LANGUAGE', '$_html/catalog/language/');
		define('DIR_TEMPLATE', '$_html/catalog/view/theme/');
		define('DIR_CONFIG', '$_html/system/config/');
		define('DIR_CACHE', '$_html/system/storage/cache/');
		define('DIR_DOWNLOAD', '$_html/system/storage/download/');
		define('DIR_LOGS', '$_html/system/storage/logs/');
		define('DIR_MODIFICATION', '$_html/system/storage/modification/');
		define('DIR_UPLOAD', '$_html/system/storage/upload/');

		// DB
		define('DB_DRIVER', 'mysqli');
		define('DB_HOSTNAME', 'localhost');
		define('DB_USERNAME', '$_slug');
		define('DB_PASSWORD', '$_pass');
		define('DB_DATABASE', '$_slug');
		define('DB_PORT', '3306');
		define('DB_PREFIX', 'oc_');
	EOF
	if [[ -s $_file ]] ; then
		cvw_file -v $_file -u root $(cvw_php -s)
		[[ -e $_dist ]] && mv $_dist $_root/config-dist.php
	elif [[ -e $_dist ]] ; then
		# pristine install
		install -o apache -m 0644 /dev/null $_file
	fi

	_file=$_html/admin/config.php
	_dist=$_html/admin/config-dist.php
	cat >$_file.tmp_VW <<-EOF
		<?php
		// HTTP
		define('HTTP_SERVER', 'https://$_canon${_uri%/}/admin/');
		define('HTTP_CATALOG', 'https://$_canon${_uri%/}/');

		// HTTPS
		define('HTTPS_SERVER', 'https://$_canon${_uri%/}/admin/');
		define('HTTPS_CATALOG', 'https://$_canon${_uri%/}/');

		// DIR
		define('DIR_APPLICATION', '$_html/admin/');
		define('DIR_SYSTEM', '$_html/system/');
		define('DIR_IMAGE', '$_html/image/');
		define('DIR_LANGUAGE', '$_html/admin/language/');
		define('DIR_TEMPLATE', '$_html/admin/view/template/');
		define('DIR_CONFIG', '$_html/system/config/');
		define('DIR_CACHE', '$_html/system/storage/cache/');
		define('DIR_DOWNLOAD', '$_html/system/storage/download/');
		define('DIR_LOGS', '$_html/system/storage/logs/');
		define('DIR_MODIFICATION', '$_html/system/storage/modification/');
		define('DIR_UPLOAD', '$_html/system/storage/upload/');
		define('DIR_CATALOG', '$_html/catalog/');

		// DB
		define('DB_DRIVER', 'mysqli');
		define('DB_HOSTNAME', 'localhost');
		define('DB_USERNAME', '$_slug');
		define('DB_PASSWORD', '$_pass');
		define('DB_DATABASE', '$_slug');
		define('DB_PORT', '3306');
		define('DB_PREFIX', 'oc_');
	EOF
	if [[ -s $_file ]] ; then
		cvw_file -v $_file -u root $(cvw_php -s)
		[[ -e $_dist ]] && mv $_dist $_root/admin-dist.php
		if [[ -d $_html/install ]] ; then
			cvw_say -s "hiding install directory"
			rm -rf $_root/install # just in case
			mv $_html/install $_root/install
		fi
	elif [[ -e $_dist ]] ; then
		# pristine install
		install -o apache -m 0644 /dev/null $_file
	fi

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p software/$_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function opencart_remove
{
	local _web=$(cvw_xml -r system/web/server)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _html
	[[ $_uri == "/" ]] && _html="/var/www/html" || _html="$_root$_uri"

	cvw_backup -z $_slug
	cvw_mysql -z $_slug $_slug
	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		if [[ $_web == "apache" && $_uri == "/" ]] ; then
			rm -rf /var/www/html
			mkdir -p /var/www/html
		fi
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				opencart_install
			else
				opencart_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

