#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_phpmyadmin - Install or remove phpMyAdmin
######                  https://www.phpmyadmin.net/
######                  https://docs.phpmyadmin.net/en/latest/setup.html#quick-install
######
###### (c) 2016-2021 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="phpMyAdmin"
_slug="phpmyadmin"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		    or: $_prog -g   Generate config template
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function phpmyadmin_generate
{
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _domain=${_fqdn#*.}

	cat <<-EOF
	    <phpmyadmin active="true">
	      <uri>/phpMyAdmin</uri>
	    </phpmyadmin>

	EOF
	exit 0
}


function phpmyadmin_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	local _secret=$(cvw_xml -r software/$_slug/secret)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _conf

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      Login URL ...............: $(cvw_url -r $_uri)
			      DB Password .............: $_pass
			      Blowfish Secret .........: $_secret
		EOF
	fi
	[[ -s /tmp/cvw/error ]] && exit 1

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci

	cvw_unpack -u apache -i $_slug $_root/app index.php

	install -o apache -g apache -d $_root/uploadDir
	install -o apache -g apache -d $_root/saveDir

	_conf="$_root/app/config.inc.php"
	cat >$_conf.tmp_VW <<-EOF
		<?php
		declare(strict_types=1);

		\$cfg['blowfish_secret'] = '$_secret';
		\$cfg['Servers'][1]['auth_type'] = 'cookie';
		\$cfg['Servers'][1]['host'] = 'localhost';
		\$cfg['Servers'][1]['compress'] = false;
		\$cfg['Servers'][1]['AllowNoPassword'] = false;

		\$cfg['UploadDir'] = '$_root/uploadDir';
		\$cfg['SaveDir'] = '$_root/saveDir';
	EOF
	cvw_file -u apache:apache -v $_conf $(cvw_php -s)

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				phpmyadmin_install
			else
				cvw_php -z $_slug
			fi
			exit 0
		;;

		g)
			phpmyadmin_generate
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

