#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_spamassassin - Install or remove SpamAssassin
######                    https://www.spamassassin.info/
######                    https://www.spamassassin.info/postfix/
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="SpamAssassin"
_slug="spamassassin"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function spamassassin_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/postfix || cvw_say -f "$_prog: requires postfix"
	local _file

	cvw_rpm -i spamassassin
if false ; then
	cvw_rpm -i spamass-milter
	cvw_rpm -i spamass-milter-postfix

	#cvw_service -s spamassassin
	#cvw_user -s spamd

	_file=/etc/mail/spamassassin/local.cf
	cvw_file -b $_file
	cat >$_file.tmp_VW <<-EOF
		# These values can be overridden by editing ~/.spamassassin/user_prefs.cf 
		# (see spamassassin(1) for details)

		# These should be safe assumptions and allow for simple visual sifting
		# without risking lost emails.

		required_hits  $(cvw_xml -r software/$_slug/required_hits)
		report_safe    $(cvw_xml -r software/$_slug/report_safe)
		required_score $(cvw_xml -r software/$_slug/required_score)
		rewrite_header $(cvw_xml -r software/$_slug/rewrite_header)
		dns_available  yes
		dns_server     127.0.0.1
	EOF
	[[ -s /tmp/cvw/error ]] && exit 1
	cvw_file -v $_file spamassassin
fi

	cvw_say -o "$_slug"
}


function spamassassin_remove
{
	local _file

	if cvw_rpm -c spamassassin ; then
		_file=/etc/postfix/master.cf
		cvw_file -e $_file "s/^\(smtp.*smtpd\).*/\1/" postfix
		cvw_file -e $_file "/spam/d" postfix
		cvw_say -h "Removing $_name"
		cvw_rpm -e spamassassin
		cvw_say -o "$_slug:remove"
	fi
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				spamassassin_install
			else
				spamassassin_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

