#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_rspamd - Install or remove RSPAMD
######              https://rspamd.com/
######              https://rspamd.com/doc/integration.html
######
###### (c) 2017 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="RSPAMD"
_slug="rspamd"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function rspamd_webui
{
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	local _hash=$(rspamadm pw --encrypt -p $_pass)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _file _conf

	_file=/etc/rspamd/local.d/worker-controller.inc
	cat >$_file.tmp_VW <<-EOF
		password = "$_hash";
	EOF
	cvw_file -v $_file rspamd

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      URL .....................: https://$_fqdn$_uri/
			      Password ................: $_pass
		EOF
	fi
	[[ -s /tmp/cvw/error ]] && exit 1

	if cvw_xml -a software/apache ; then
		_conf=$(cvw_apache -c)
		cat >>$_conf.tmp_VW <<-EOF

			   ProxyPass $_uri/        http://127.0.0.1:11334/
			   ProxyPassReverse $_uri/ http://127.0.0.1:11334/
		EOF
	fi

	cvw_url -a "$_name" $_uri

	cvw_firewall -t 11334
}


function rspamd_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/postfix || cvw_say -f "$_prog: requires postfix"
	local _milter=$(cvw_xml -r software/$_slug/milter)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _file

	cvw_yum -a rspamd
	cvw_rpm -i rspamd
	cvw_service -s rspamd

	_file=/etc/rspamd/local.d/worker-proxy.inc
	cat >$_file.tmp_VW <<-EOF
		milter = yes;
		timeout = 120s;
		upstream "local" {
		  default = yes;
		  self_scan = true;
		}
		count = 4;
		max_retries = 5;
		discard_on_reject = false;
		quarantine_on_reject = false;
		spam_header = "X-Spam";
		reject_message = "Spam message rejected";
	EOF
	cvw_file -v $_file rspamd

	if cvw_xml -c software/$_slug/password ; then
		rspamd_webui
	fi

	_file=/etc/rspamd/local.d/milter_headers.conf
	cat >$_file.tmp_VW <<-EOF
		extended_spam_headers = true;
	EOF
	cvw_file -v $_file rspamd

	echo "20 $_milter" >>/tmp/cvw/postfix.milters

	cvw_say -o "$_slug"
}


function rspamd_remove
{
	local _file

	if cvw_rpm -c rspamd ; then
		_file=/etc/postfix/master.cf
		cvw_file -e $_file "s/^\(smtp.*smtpd\).*/\1/" postfix
		cvw_file -e $_file "/spam/d" postfix

		cvw_say -h "Removing $_name"

		cvw_rpm -e rspamd
		rm -rf /etc/rspamd

		cvw_say -o "$_slug:remove"
	fi
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				rspamd_install
			else
				rspamd_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

