#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_serendipity - Install or remove Serendipity
######                   http://www.s9y.org/
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Serendipity"
_slug="serendipity"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function serendipity_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _app=$_root/app
	local _conf _file _subdir

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      DB Name / User ..........: $_slug
			      DB Pass .................: $_pass
			      Admin Login .............: $(cvw_xml -r software/$_slug/admin/username)
			      Admin Password ..........: $(cvw_xml -r software/$_slug/admin/password)
			      Admin Fullname ..........: $(cvw_xml -r software/$_slug/admin/fullname)
			      Admin E-Mail ............: $(cvw_xml -r software/$_slug/admin/email)
			      Blog-Title ..............: $(cvw_xml -r software/$_slug/title)
			      Blog-Beschreibung .......: $(cvw_xml -r software/$_slug/subtitle)
			      Login URL ...............: $(cvw_url -r $_uri)index.php?/admin"
		EOF
		[[ -s /tmp/cvw/error ]] && exit 1
	fi

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci

	cvw_unpack -i $_slug $_app index.php
	chmod -R go-w $_app
	for _subdir in archives plugins templates_c uploads spamblock ; do
		mkdir -p $_app/$_subdir
	done

	_file="serendipity_config_local.inc.php"
	if [[ -s $_app/.htaccess ]] ; then
		chmod 0644 $_app/.htaccess $_app/$_file
		chmod 0755 $_app
		cp $_app/.htaccess $_root/htaccess
		cp $_app/$_file $_root/$_file
		cvw_borgclient -m $_slug
		cvw_borgclient -d $_app/archives
		cvw_borgclient -d $_app/plugins
		cvw_borgclient -d $_app/templates_c
		cvw_borgclient -d $_app/uploads
		cvw_borgclient -d $_app/spamblock

	else
		cvw_say -a "waiting for installation"
	fi
	chown -R apache:apache $_app

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function serendipity_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		cvw_mysql -z $_slug $_slug
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				serendipity_install
			else
				serendipity_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

