#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_randshop - Install or remove randshop eCommerce
######                http://www.randshop.com/
######                http://www.wiki.randshop.com/Randshop-Installation
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="randshop eCommerce"
_slug="randshop"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function randshop_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _file _subdir

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci

	cvw_unpack -m -s -i $_slug $_root/app index.php

	for _subdir in data admin images/dbimages includes/libraries/mpdf/tmp ; do
		mkdir -p $_root/app/$_subdir
		chown -R apache $_root/app/$_subdir
	done

	_file=$_root/app/sitemap.xml
	[[ -s $_file ]] || touch $_file
	chown apache:apache $_file

	_file=$_root/app/conf/config.inc.php
	if grep -q "INSTALL.*true" $_file ; then
		cvw_say -a "$_name waiting for install and admin protection"
		chown apache:apache $_file
	else
		if [[ -d $_root/app/install ]] ; then
			cvw_say -s "hiding install directory"
			rm -rf $_root/install # just in case
			mv $_root/app/install $_root/install
			chown -R root:root $_root/install
		fi
		cvw_borgclient -m $_slug
		cvw_borgclient -d $_root/app/data
		cvw_borgclient -d $_root/app/images/dbimages
	fi

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function randshop_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		cvw_mysql -z $_slug $_slug
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				randshop_install
			else
				randshop_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

