#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_openproject - Install or remove OpenProject
######                   https://www.openproject.org/
######                   https://www.openproject.org/download-and-installation/
######                   https://docs.openproject.org/installation-and-operations/installation/docker/
######                   https://docs.openproject.org/installation-and-operations/installation/packaged/#el-7
######                   https://docs.openproject.org/installation-and-operations/configuration/environment/
######                   https://docs.openproject.org/installation-and-operations/configuration/outbound-emails/
######
###### (c) 2016-2020 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="OpenProject"
_slug="openproject"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		    or: $_prog -g   Generate config template
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function openproject_generate
{
	cat <<-EOF
	    <openproject active="true">
	      <release>10</release>
	    </openproject>

	EOF
	exit 0
}


function openproject_install
{
	cvw_xml -a software/docker || cvw_say -f "$_prog: requires docker"
	cvw_say -h "Installing $_name"
	local _release=$(cvw_xml -R software/$_slug/release 10)
	local _uri=$(cvw_xml -r software/$_slug/uri)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _tmpl _file

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      Release .................: $_release
		EOF
	fi
	[[ -s /tmp/cvw/error ]] && exit 1

	if [[ -d /root/openproject ]] ; then
		if grep -q -s upgrade /tmp/cvw/updating ; then
			(cd /root/openproject && git pull)
			[[ $? -eq 0 ]] || exit 1
		fi
	else
		git clone --depth=1 --branch=stable/$_release https://github.com/opf/openproject
		[[ $? -eq 0 ]] || exit 1
	fi

	_tmpl="/var/lib/cvw_cfg/files/misc/openproject.yml"
	_file="/root/openproject/docker-compose.yml"
	cvw_file -b $_file
	cp $_tmpl $_file || cvw_say -s "can't find $_tmpl"
	cvw_file -e $_file "s|\(openproject/community:\).*|\1$_release|"

	if cvw_xml -a software/apache ; then
		cat >/tmp/cvw/apache.block <<-EOF

		    RewriteRule "^\$" "/" [R,L]
		    <Location "/">
		      RequestHeader    set X-Forwarded-Proto 'https'
		      ProxyPass        http://127.0.0.1:8080/
		      ProxyPassReverse http://127.0.0.1:8080/
		    </Location>
		EOF
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function openproject_remove
{
	if [[ -d /root/openproject ]] ; then
		cvw_say -h "Please remove $_name manually"
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":ig" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				openproject_install
			else
				openproject_remove
			fi
			exit 0
		;;

		g)
			openproject_generate
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

