#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_mount - Install or remove CIFS Utils
######             https://wiki.samba.org/index.php/LinuxCIFS_utils
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="CIFS Utils"
_slug="mount"

_fstab="/etc/fstab"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		    or: $_prog -g   Generate config template
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function mount_template
{
	cat <<-EOF
	    <mount id="example" active="true">
	      <mountpoint>/mount/point</mountpoint>
	      <server>//host.example.com/path</server>
	      <username>username</username>
	      <password>password</password>
	    </mount>

	EOF
	exit 0
}


function mount_install
{
	local _id="$1"
	local _base="system/$_slug:$_id"
	local _host=$(cvw_xml -r $_base/host)
	local _user=$(cvw_xml -r $_base/user)
	local _pass=$(cvw_xml -r $_base/password)
	local _path=$(cvw_xml -r $_base/mountpoint)
	local _owner=$(cvw_xml -R $_base/owner root)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _uid _gid

	cvw_rpm -i cifs-utils

	if [[ $_owner != root ]] ; then
		cvw_user -s $_owner
	fi
	_uid=$(id -u $_owner 2>>/tmp/cvw/error)
	[[ -s /tmp/cvw/error ]] && exit 1
	_gid=$(id -g $_owner)

	if ! grep -q $_path $_fstab ; then
		cvw_say -s "mounting $_path"
	fi

	install -o $_owner -g $_owner -d $_path
	grep -v $_path $_fstab >$_fstab.tmp_VW
	echo "$_host $_path cifs rw,user=$_user,pass=$_pass,uid=$_uid,gid=$_gid,iocharset=utf8 0 0" >>$_fstab.tmp_VW
	cvw_file -v $_fstab
}


function mount_remove
{
	local _id="$1"
	local _base="system/$_slug:$_id"
	local _path=$(cvw_xml -r $_base/mountpoint)

	if grep -q $_path $_fstab ; then
		cvw_say -s "unmounting $_path"
	fi

	grep -v $_path $_fstab >$_fstab.tmp_VW
	cvw_file -v $_fstab

	if ! grep -q cifs $_fstab ; then
		cvw_rpm -e cifs-utils
	fi
}


while getopts ":ig" opt ; do
	case $opt in
		i)
			cvw_xml -u system/$_slug | sort | while read _id ; do
				mount_remove $_id
			done
			cvw_xml -i system/$_slug | sort | while read _id ; do
				mount_install $_id
			done
			mount -a
			exit 0
		;;

		g)
			mount_generate
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

