#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_processwire - Install or remove ProcessWire
######                   https://processwire.com/
######                   https://processwire.com/docs/install/new/
######
###### (c) 2017 Volker Wiegand <volker.wiegand@cvw.de>
######          This file is part of "CVW Config"
######          See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="ProcessWire"
_slug="processwire"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function processwire_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _file _subdir

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci
	cvw_backup -m $_slug -u $_slug -p $_pass $_slug $_root/app

	cvw_unpack -u apache -i $_slug $_root/app index.php

	_file=$_root/app/.htaccess
	if [[ ! -r $_file ]] ; then
		cp $_root/app/htaccess.txt $_file.tmp_VW
		cvw_file -v $_file $(cvw_php -s)
	fi
	if [[ "$_uri" == "/" ]] ; then
		cvw_file -e $_file "s|^ \( RewriteBase\).*|  #\1 /pw/|" $(cvw_php -s)
	else
		cvw_file -e $_file "s|# \(RewriteBase /pw/\)|\1|" $(cvw_php -s)
		cvw_file -e $_file "s|^\(  RewriteBase\).*|\1 $_uri/|" $(cvw_php -s)
	fi

	_file=$_root/app/site/config.php
	if grep -q dbHost $_file ; then
		cvw_file -e $_file "s/dbHost.*/dbHost = 'localhost';/" $(cvw_php -s)
		cvw_file -e $_file "s/dbName.*/dbName = '$_slug';/" $(cvw_php -s)
		cvw_file -e $_file "s/dbUser.*/dbUser = '$_slug';/" $(cvw_php -s)
		cvw_file -e $_file "s/dbPass.*/dbPass = '$_pass';/" $(cvw_php -s)
		cvw_file -e $_file "s/dbPort.*/dbPort = '3306';/" $(cvw_php -s)
		chmod 0400 $_file
	else
		chmod 0644 $_file
	fi

	if [[ -d /var/local/backup/$_slug/last/mysql && \
	      -d /var/local/backup/$_slug/last/dirs  && \
	      -x /usr/local/bin/bkup.$_slug          && \
	      -x /usr/local/bin/rstr.$_slug ]] ; then
		cvw_say -s "updating / syncing backup"
		/usr/local/bin/bkup.$_slug
	fi

	_file="/etc/profile.d/alias_$_slug.sh"
	cat >$_file.tmp_VW <<-EOF
		#
		# shell aliases for processwire
		#

		alias pw-p='cd /var/local/processwire/app'
		alias pw-w='cd /var/local/processwire/app/wire'
		alias pw-s='cd /var/local/processwire/app/site'
		alias pw-a='cd /var/local/processwire/app/site/assets'
		alias pw-m='cd /var/local/processwire/app/site/modules'
		alias pw-t='cd /var/local/processwire/app/site/templates'
	EOF
	cvw_file -v $_file

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


function processwire_remove
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	cvw_backup -z $_slug
	cvw_mysql -z $_slug $_slug
	if [[ -d $_root ]] ; then
		cvw_say -h "Removing $_name"
		rm -rf $_root
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				processwire_install
			else
				processwire_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

