#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_roundcube - Install or remove Roundcube webmail
######                 https://roundcube.net/
######                 https://github.com/roundcube/roundcubemail/wiki/Installation
######
###### (c) 2016-2019 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Roundcube webmail"
_slug="roundcube"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		    or: $_prog -g   Generate config template
		    or: $_prog -x   Hide the installation task
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function generate
{
	cat <<-EOF
	    <$_slug active="true">
	      <uri>/webmail</uri>
	      <alias>/roundcube</alias>
	      <password>$(cvw -p 20)</password>
	      <key>$(cvw -p 10).--.$(cvw -p 10)</key>
	    </$_slug>

	EOF
	exit 0
}


function roundcube_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _lang=$(cvw_xml -r system/language)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	local _key=$(cvw_xml -r software/$_slug/key)
	local _admin=$(cvw_xml -R software/$_slug/admin admin)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _conf=$_root/app/config/config.inc.php
	local _file _installer _plugin _plugins

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      URL .....................: https://$_fqdn$_uri/
			      Admin Email .............: $_admin@${_fqdn#*.}
			      Admin Password ..........: $(cvw_user -p $_admin)
		EOF
		[[ -s /tmp/cvw/error ]] && exit 1
	fi

	cvw_backup -m $_slug -u $_slug -p $_pass $_slug \
		$_root/app/logs \
		$_root/app/temp

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci

	cvw_unpack -i $_slug $_root/app index.php
	for _subdir in temp logs ; do
		mkdir -p $_root/app/$_subdir
		chown -R apache $_root/app/$_subdir
	done

	if grep -q -s $_pass $_conf ; then
		chmod 0700 $_root/app/installer
		_installer="false"

		cvw_borgclient -m $_slug
		cvw_borgclient -d $_root/app/logs
		cvw_borgclient -d $_root/app/temp
	else
		cvw_say -a "Installer URL ...........: $(cvw_url -r $_uri)installer/"
		_installer="true"
	fi

	_plugins=""
	for _plugin in $(cvw_xml -l software/$_slug/plugin | sort) ; do
		if [[ -n "$_plugins" ]] ; then
			_plugins="$_plugins, "
		fi
			_plugins="$_plugins'$_plugin'"
	done
	cat >$_conf.tmp_VW <<-EOF
		<?php
		\$config['db_dsnw']           = 'mysql://$_slug:$_pass@localhost/$_slug';
		\$config['default_host']      = 'localhost';
		\$config['support_url']       = 'mailto:postmaster@${_fqdn#*.}';
		\$config['des_key']           = '$_key';
		\$config['product_name']      = '$_name';
		\$config['plugins']           = array($_plugins);
		\$config['language']          = '$_lang';
		\$config['spellcheck_engine'] = 'googie';
		\$config['enable_installer']  = $_installer;
	EOF
	cvw_file -v $_conf $(cvw_php -s)

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		_file=/tmp/cvw/apache.block
		echo "" >$_file
		echo "   Alias $_uri $_root/app" >>$_file
		for _alias in $(cvw_xml -l software/$_slug/alias | sort) ; do
			echo "   Alias $_alias $_root/app" >>$_file
		done
		cat >>$_file <<-EOF
			   <Directory $_root/app>
			      Options Indexes FollowSymLinks MultiViews
			      <IfModule mod_passenger.c>
			         PassengerEnabled off
			      </IfModule>
			      AllowOverride all
			      Require all granted
			   </Directory>
		EOF
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri
	for _alias in $(cvw_xml -l software/$_slug/alias | sort) ; do
		cvw_url -a "$_name" $_alias
	done

	cvw_say -o "$_slug"
}


while getopts ":ig" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				roundcube_install
			else
				cvw_php -z $_slug
			fi
			exit 0
		;;

		g)
			generate
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

