#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_nextcloud - Install or remove Nextcloud
######                 https://nextcloud.com/
######                 https://docs.nextcloud.com/server/16/admin_manual/installation/index.html
######                 https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/occ_command.html
######
###### (c) 2016-2021 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="Nextcloud"
_slug="nextcloud"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		    or: $_prog -g   Generate config template
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function nextcloud_generate
{
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _domain=${_fqdn#*.}

	cat <<-EOF
	    <nextcloud active="true" wellknown="true">
	      <release>19_0_1</release>
	      <uri>/cloud</uri>
	      <password>$(cvw -p 20)</password>
	      <loglevel>1</loglevel>
	      <admin>
	        <name>Cloud Admin</name>
	        <password>$(cvw -p 20)</password>
	      </admin>
	    </nextcloud>

	EOF
	exit 0
}


function nextcloud_occ
{
	local _root=$(cvw_xml -r system/app_root)/$_slug

	cvw_user -r apache -d $_root/app php occ $*
	[[ $? -eq 0 ]] || exit 1
}


function nextcloud_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	local _loglvl=$(cvw_xml -r software/$_slug/loglevel)
	local _adm_name=$(cvw_xml -r software/$_slug/admin/name)
	local _adm_pass=$(cvw_xml -r software/$_slug/admin/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _conf _file _version

	if [[ -d $_root/app ]] ; then
		_version=$(cvw_user -R apache -d $_root/app php occ status --version)
	else
		_version="not installed"
	fi

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      Installed version .......: $_version
			      Database password .......: $_pass
			      Login URL ...............: $(cvw_url -r $_uri)index.php/login
			      Admin Name ..............: $_adm_name
			      Admin Password ..........: $_adm_pass
		EOF
	fi
	[[ -s /tmp/cvw/error ]] && exit 1

	cvw_mysql -c $_slug $_slug $_pass utf8mb4_general_ci

	cvw_unpack -u apache -i $_slug $_root/app index.php

	_conf="$_root/app/config/config.php"
	if [[ -s $_conf ]] ; then
		nextcloud_occ maintenance:mode --on
		_exist=1
	else
		cvw_user -r apache -d $_root/app \
			php occ maintenance:install \
			--database      "mysql" \
			--database-name "$_slug"  \
			--database-user "$_slug" \
			--database-pass "$_pass" \
			--admin-user    "$_adm_name" \
			--admin-pass    "$_adm_pass"
		[[ $? -eq 0 ]] || exit 1
	fi

	if [[ ! -d $_root/data ]] ; then
		cvw_say -s "installing data dir outside docroot"
		install -d $_root/data
	fi
	touch $_root/data/.ocdata
	chown -R apache:apache $_root/data
	if ! grep -q "$_root/data" $_conf ; then
		nextcloud_occ config:system:set datadirectory --value=$_root/data
	fi

	if [[ ! -d $_root/log ]] ; then
		install -o apache -g apache -d $_root/log
	fi
	if ! grep -q "logfile" $_conf ; then
		nextcloud_occ config:system:set logfile --value=$_root/log/nextcloud.log
		nextcloud_occ config:system:set loglevel --value=$_loglvl
	fi

	if [[ ! -d $_root/skeleton ]] ; then
		install -o apache -g apache -d $_root/skeleton
	fi
	if ! grep -q "skeletondirectory" $_conf ; then
		nextcloud_occ config:system:set skeletondirectory --value=$_root/skeleton
	fi

	if ! grep -q "overwriteprotocol" $_conf ; then
		nextcloud_occ config:system:set overwriteprotocol --value=https
	fi

	if ! grep -q "$_fqdn" $_conf ; then
		nextcloud_occ config:system:set trusted_domains 1 --value=$_fqdn
	fi
	if ! grep -q "APCu" $_conf ; then
		nextcloud_occ config:system:set memcache.local --value=\\\\OC\\\\Memcache\\\\APCu
	fi
	if ! grep -q "default_language" $_conf ; then
		nextcloud_occ config:system:set default_language --value=de
	fi
	if ! grep -q "default_phone_region" $_conf ; then
		nextcloud_occ config:system:set default_phone_region --value=DE
	fi

	if grep -q -s upgrade /tmp/cvw/updating ; then
		nextcloud_occ config:system:set mysql.utf8mb4 --type boolean --value=true
		if [[ $_exist ]] ; then
			nextcloud_occ maintenance:repair
		fi
		nextcloud_occ db:convert-filecache-bigint
		nextcloud_occ db:add-missing-indices
		nextcloud_occ db:add-missing-columns
		if [[ $_version =~ 20\. ]] ; then
			nextcloud_occ db:add-missing-primary-keys
		fi
	fi

	nextcloud_occ maintenance:mode --off

	if nextcloud_occ app:list | grep -q groupfolders ; then
		nextcloud_occ groupfolders:trashbin:cleanup --force
	fi

	mkdir -p $_root/cron
	_file=$_root/cron/apache.crontab
	cat >$_file.tmp_VW <<-EOF
		*/5  *  *  *  * php -f $_root/app/cron.php
	EOF
	cvw_file -v $_file
	crontab -u apache $_file

	if cvw_xml -a software/nginx ; then
		_file="/tmp/cvw/nginx.options"
		cat >$_file <<-EOF
			root $_root/app;
			    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
			    add_header X-Content-Type-Options nosniff;
			    add_header X-Frame-Options "SAMEORIGIN";
			    add_header X-XSS-Protection "1; mode=block";
			    add_header X-Robots-Tag none;
			    gzip off;
			    rewrite ^${_uri%/}/caldav(.*)\$ ${_uri%/}/remote.php/caldav\$1 redirect;
			    rewrite ^${_uri%/}/carddav(.*)\$ ${_uri%/}/remote.php/carddav\$1 redirect;
			    rewrite ^${_uri%/}/webdav(.*)\$ ${_uri%/}/remote.php/webdav\$1 redirect;
			    index index.php;
			    error_page 403 ${_uri%/}/core/templates/403.php;
			    error_page 404 ${_uri%/}/core/templates/404.php;

			   # location ~ ^${_uri%/}/(?:\\.htaccess|data|config|db_structure\\.xml|README) {
			   #   deny all;
			   # }
		EOF
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cat >/tmp/cvw/apache.block <<-EOF

			   Alias $_uri $_root/app
			   <Directory $_root/app>
			      Options +FollowSymlinks
			      AllowOverride All
			      Satisfy Any
			      Require all granted
			      <IfModule mod_dav.c>
			         Dav off
			      </IfModule>
			      <IfModule mod_passenger.c>
			         PassengerEnabled off
			      </IfModule>
			      <IfModule mod_headers.c>
			         Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
			      </IfModule>
			      SetEnv HOME $_root/app
			      SetEnv HTTP_HOME $_root/app
			   </Directory>
			   <IfModule mod_rewrite.c>
			     RewriteEngine on
			     RewriteRule ^/\\.well-known/host-meta $_uri/public.php?service=host-meta [QSA,L]
			     RewriteRule ^/\\.well-known/host-meta\\.json $_uri/public.php?service=host-meta-json [QSA,L]
			     RewriteRule ^/\\.well-known/webfinger $_uri/public.php?service=webfinger [QSA,L]
			     RewriteRule ^/\\.well-known/nodeinfo $_uri/public.php?service=nodeinfo [QSA,L]
		EOF
		if cvw_xml -t software/$_slug/wellknown ; then
			cat >>/tmp/cvw/apache.block <<-EOF
				     RewriteRule ^/\\.well-known/carddav $_uri/remote.php/dav/ [R=301,L]
				     RewriteRule ^/\\.well-known/caldav  $_uri/remote.php/dav/ [R=301,L]
			EOF
		fi
		cat >>/tmp/cvw/apache.block <<-EOF
			   </IfModule>
		EOF
		cvw_apache -p $_slug
	fi

	if [[ -x /usr/local/bin/bb.create ]] ; then
		_bkup="/etc/cron.daily/bkup.$_slug"
		cat >$_bkup.tmp_VW <<-EOF
			#!/bin/bash
			set -e
			cd $_root

			mkdir -p mysqldump
			/usr/bin/mysqldump -u$_slug -p$_pass $_slug >mysqldump/$_slug.sql

			/usr/local/bin/bb.create $_slug app data mysqldump
			/usr/local/bin/bb.prune  $_slug
		EOF
		cvw_file -m 0775 -v $_bkup
		ln -nfs $_bkup /usr/local/bin/bkup.$_slug
		rm -f /usr/local/bin/rstr.$_slug
	else
		cvw_backup -m $_slug -u $_slug -p $_pass $_slug $_root/data
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				nextcloud_install
			else
				cvw_php -z $_slug
			fi
			exit 0
		;;

		g)
			nextcloud_generate
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

