#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_proftpd - Install or remove ProFTPD FTP server
######               http://www.proftpd.org/
######               https://www.thomas-krenn.com/de/wiki/FTP-Server_unter_Debian_einrichten
######
###### (c) 2016-2021 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="ProFTPD"
_slug="proftpd"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function proftpd_install
{
	cvw_say -h "Installing $_name"
	local _conf="/etc/proftpd/proftpd.conf"

	cvw_rpm -i proftpd
	cvw_rpm -i proftpd-utils
	cvw_rpm -i ftp

	cvw_service -s proftpd
	cvw_firewall -s ftp

	cvw_say -o "$_slug"
}


function proftpd_remove
{
	set +e

	if cvw_rpm -c proftpd ; then
		cvw_say -h "Removing $_name"
		cvw_service -d proftpd
		cvw_rpm -e proftpd
		cvw_rpm -e proftpd-utils
		rm -rf /etc/proftpd
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				proftpd_install
			else
				proftpd_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

