#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_open3a - Install or remove open3A Faktura
######              https://www.open3a.de/
######              https://www.open3a.de/page-Installation/WebserverSetup
######
###### (c) 2016-2021 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="open3A Faktura"
_slug="open3a"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function open3a_install
{
	cvw_say -h "Installing $_name"
	cvw_xml -a software/mysql || cvw_say -f "$_prog: requires mysql"
	cvw_xml -a software/php   || cvw_say -f "$_prog: requires php"
	local _root=$(cvw_xml -r system/app_root)/$_slug
	local _uri=$(cvw_xml -r software/$_slug/uri)
	local _pass=$(cvw_xml -r software/$_slug/password)
	[[ -s /tmp/cvw/error ]] && exit 1
	local _file _subdir

	if [[ -s /tmp/cvw/info ]] ; then
		cat >>/tmp/cvw/info <<-EOF
			    ====== $_name ======
			      Database Name ...........: $_slug
			      Database Password .......: $_pass
			      Login URL ...............: $(cvw_url -r $_uri)
		EOF
	fi

	cvw_mysql -c $_slug $_slug $_pass utf8_general_ci

	cvw_unpack -m -s -i $_slug $_root/app index.php

	for _subdir in specifics system/Backup system/DBData ; do
		mkdir -p $_root/app/$_subdir
		chown -R apache:apache $_root/app/$_subdir
	done

	find /var/lib/cvw_cfg/files/misc -name "open3a.*.sql.gz" | while read _file ; do
		cvw_say -s "Backup $_file"
		install -o apache -g apache $_file $_root/app/system/Backup
	done

	if [[ -x /usr/local/bin/bb.create ]] ; then
		_bkup="/etc/cron.daily/bkup.$_slug"
		cat >$_bkup.tmp_VW <<-EOF
			#!/bin/bash
			set -e
			cd $_root

			mkdir -p mysqldump
			/usr/bin/mysqldump -u$_slug -p$_pass $_slug >mysqldump/$_slug.sql

			/usr/local/bin/bb.create $_slug app mysqldump
		EOF
		cvw_file -m 0775 -v $_bkup
		ln -nfs $_bkup /usr/local/bin/bkup.$_slug
		rm -f /usr/local/bin/rstr.$_slug
	else
		cvw_backup -m $_slug -u $_slug -p $_pass $_slug \
			$_root/app/specifics \
			$_root/app/system/Backup \
			$_root/app/system/DBData
	fi

	if cvw_xml -a software/nginx ; then
		cvw_nginx -p $_slug
	fi

	if cvw_xml -a software/apache ; then
		cvw_apache -p $_slug
	fi

	cvw_url -a "$_name" $_uri

	cvw_say -o "$_slug"
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				open3a_install
			else
				cvw_php -z $_slug
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

