#!/bin/bash
# vim: set ts=8 tw=0 noet :

#################################################################################
######
###### cvw_haproxy - Install or remove HAProxy
######               http://www.haproxy.org/
######
###### (c) 2016-2017 Volker Wiegand <volker.wiegand@cvw.de>
######               This file is part of "CVW Config"
######               See LICENSE for copyright information
######
######          TODO HAProxy configuration is not implemented yet
######
#################################################################################

# Exit on error
set -e -o pipefail

# Remember the args
_prog=${0##*/}
_args="$*"
_name="HAProxy"
_slug="haproxy"


function usage
{
	rm -rf /tmp/cvw_error
	cat >/tmp/cvw_error <<-EOF
		Syntax: $_prog -i   Install or remove $_name
		Called with: '$_prog $_args'
	EOF

	if [[ -d /tmp/cvw ]] ; then
		cat /tmp/cvw_error >>/tmp/cvw/error
	else
		cat /tmp/cvw_error >&2
	fi
	rm -f /tmp/cvw_error

	exit 1
}


function haproxy_install
{
	cvw_say -h "Installing $_name"
	local _fqdn=$(cvw_xml -r host/fqdn)
	local _port=$(cvw_xml -r software/$_slug/port)
	local _ssl_port=$(cvw_xml -r software/$_slug/ssl_port)
	[[ -s /tmp/cvw/error ]] && exit 1

	cvw_rpm -i haproxy
	cvw_service -S haproxy

	if cvw_xml -t software/$_slug/public ; then
		cvw_firewall -t $_port
		cvw_firewall -t $_ssl_port
	fi

	cvw_say -o "$_slug"
}


function haproxy_remove
{
	if cvw_rpm -c haproxy ; then
		cvw_say -h "Removing $_name"

		cvw_service -d haproxy
		cvw_rpm -e haproxy

		rm -f /tmp/cvw/error
		cvw_say -o "$_slug:remove"
	fi

	rm -f /tmp/cvw/error
}


while getopts ":i" opt ; do
	case $opt in
		i)
			if cvw_xml -a software/$_slug ; then
				haproxy_install
			else
				haproxy_remove
			fi
			exit 0
		;;

		\?)
			usage
		;;
	esac
done
shift $(($OPTIND-1))

usage

